// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package unbound

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *dnsblResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages the Unbound DNS blocklist (DNSBL) settings on OPNsense.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource identifier.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"enabled":     schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Enable DNS-based blocklisting."},
			"safe_search": schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Force safe search on supported search engines."},
			"type":        schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, MarkdownDescription: "Built-in blocklist feeds to enable."},
			"lists":       schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, MarkdownDescription: "Custom blocklist URL entries to apply."},
			"whitelists":  schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, MarkdownDescription: "Whitelist (allow) domain pattern entries."},
			"blocklists":  schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, MarkdownDescription: "Blocklist (deny) domain pattern entries."},
			"wildcards":   schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, MarkdownDescription: "Wildcard domain block entries."},
			"address":     schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Destination address for blocked responses (empty = 0.0.0.0).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"nxdomain":    schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Return NXDOMAIN for blocked entries instead of an address."},
		},
	}
}
