// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package unbound

import (
	"context"
	"errors"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var (
	_ resource.Resource                = &dnsblResource{}
	_ resource.ResourceWithImportState = &dnsblResource{}
)

// dnsblID is the synthetic identifier for this singleton settings object.
const dnsblID = "unbound-dnsbl"

var dnsblReqOpts = opnsense.ReqOpts{
	GetEndpoint:         "/api/unbound/settings/get",
	UpdateEndpoint:      "/api/unbound/settings/set",
	ReconfigureEndpoint: "/api/unbound/service/reconfigure",
	Monad:               "unbound.dnsbl",
}

type dnsblResource struct{ client *opnsense.Client }

func newDNSBLResource() resource.Resource { return &dnsblResource{} }

func (r *dnsblResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_unbound_dnsbl"
}

func (r *dnsblResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	r.client = client
}

func (r *dnsblResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan DNSBLResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := opnsense.UpdateSingleton(ctx, r.client, dnsblReqOpts, plan.toAPI(ctx)); err != nil {
		resp.Diagnostics.AddError("Error applying the Unbound DNS blocklist (DNSBL) settings", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.GetSingleton[dnsblAPIResponse](ctx, r.client, dnsblReqOpts)
	if err != nil {
		resp.Diagnostics.AddError("Error reading the Unbound DNS blocklist (DNSBL) settings after apply", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, dnsblID)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *dnsblResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state DNSBLResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	result, err := opnsense.GetSingleton[dnsblAPIResponse](ctx, r.client, dnsblReqOpts)
	if err != nil {
		var nf *opnsense.NotFoundError
		if errors.As(err, &nf) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading the Unbound DNS blocklist (DNSBL) settings", fmt.Sprintf("%s", err))
		return
	}
	state.fromAPI(ctx, result, dnsblID)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *dnsblResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan DNSBLResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := opnsense.UpdateSingleton(ctx, r.client, dnsblReqOpts, plan.toAPI(ctx)); err != nil {
		resp.Diagnostics.AddError("Error updating the Unbound DNS blocklist (DNSBL) settings", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.GetSingleton[dnsblAPIResponse](ctx, r.client, dnsblReqOpts)
	if err != nil {
		resp.Diagnostics.AddError("Error reading the Unbound DNS blocklist (DNSBL) settings after update", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, dnsblID)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// Delete is a no-op for the singleton; destroy only removes it from state.
func (r *dnsblResource) Delete(_ context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse) {
}

func (r *dnsblResource) ImportState(ctx context.Context, _ resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), types.StringValue(dnsblID))...)
}
