// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package unbound

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/tfconv"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// GeneralResourceModel is the Terraform state model for opnsense_unbound_general.
type GeneralResourceModel struct {
	ID                   types.String `tfsdk:"id"`
	Enabled              types.Bool   `tfsdk:"enabled"`
	Port                 types.String `tfsdk:"port"`
	Stats                types.Bool   `tfsdk:"stats"`
	ActiveInterface      types.Set    `tfsdk:"active_interface"`
	DNSSEC               types.Bool   `tfsdk:"dnssec"`
	DNS64                types.Bool   `tfsdk:"dns64"`
	DNS64Prefix          types.String `tfsdk:"dns64_prefix"`
	NoAAAARecords        types.Bool   `tfsdk:"no_aaaa_records"`
	RegisterDHCP         types.Bool   `tfsdk:"register_dhcp"`
	RegisterDHCPDomain   types.String `tfsdk:"register_dhcp_domain"`
	RegisterDHCPStatic   types.Bool   `tfsdk:"register_dhcp_static"`
	NoRegisterLinkLocal6 types.Bool   `tfsdk:"no_register_link_local6"`
	NoRegisterRecords    types.Bool   `tfsdk:"no_register_records"`
	TXTSupport           types.Bool   `tfsdk:"txt_support"`
	CacheFlush           types.Bool   `tfsdk:"cache_flush"`
	LocalZoneType        types.String `tfsdk:"local_zone_type"`
	OutgoingInterface    types.Set    `tfsdk:"outgoing_interface"`
	EnableWPAD           types.Bool   `tfsdk:"enable_wpad"`
}

type generalAPIResponse struct {
	Enabled              string                   `json:"enabled"`
	Port                 string                   `json:"port"`
	Stats                string                   `json:"stats"`
	ActiveInterface      opnsense.SelectedMapList `json:"active_interface"`
	DNSSEC               string                   `json:"dnssec"`
	DNS64                string                   `json:"dns64"`
	DNS64Prefix          string                   `json:"dns64prefix"`
	NoAAAARecords        string                   `json:"noarecords"`
	RegisterDHCP         string                   `json:"regdhcp"`
	RegisterDHCPDomain   string                   `json:"regdhcpdomain"`
	RegisterDHCPStatic   string                   `json:"regdhcpstatic"`
	NoRegisterLinkLocal6 string                   `json:"noreglladdr6"`
	NoRegisterRecords    string                   `json:"noregrecords"`
	TXTSupport           string                   `json:"txtsupport"`
	CacheFlush           string                   `json:"cacheflush"`
	LocalZoneType        opnsense.SelectedMap     `json:"local_zone_type"`
	OutgoingInterface    opnsense.SelectedMapList `json:"outgoing_interface"`
	EnableWPAD           string                   `json:"enable_wpad"`
}

type generalAPIRequest struct {
	Enabled              string `json:"enabled"`
	Port                 string `json:"port,omitempty"`
	Stats                string `json:"stats"`
	ActiveInterface      string `json:"active_interface,omitempty"`
	DNSSEC               string `json:"dnssec"`
	DNS64                string `json:"dns64"`
	DNS64Prefix          string `json:"dns64prefix,omitempty"`
	NoAAAARecords        string `json:"noarecords"`
	RegisterDHCP         string `json:"regdhcp"`
	RegisterDHCPDomain   string `json:"regdhcpdomain,omitempty"`
	RegisterDHCPStatic   string `json:"regdhcpstatic"`
	NoRegisterLinkLocal6 string `json:"noreglladdr6"`
	NoRegisterRecords    string `json:"noregrecords"`
	TXTSupport           string `json:"txtsupport"`
	CacheFlush           string `json:"cacheflush"`
	LocalZoneType        string `json:"local_zone_type,omitempty"`
	OutgoingInterface    string `json:"outgoing_interface,omitempty"`
	EnableWPAD           string `json:"enable_wpad"`
}

func (m *GeneralResourceModel) toAPI(ctx context.Context) *generalAPIRequest {
	return &generalAPIRequest{
		Enabled:              opnsense.BoolToString(m.Enabled.ValueBool()),
		Port:                 m.Port.ValueString(),
		Stats:                opnsense.BoolToString(m.Stats.ValueBool()),
		ActiveInterface:      tfconv.SetToCSV(ctx, m.ActiveInterface),
		DNSSEC:               opnsense.BoolToString(m.DNSSEC.ValueBool()),
		DNS64:                opnsense.BoolToString(m.DNS64.ValueBool()),
		DNS64Prefix:          m.DNS64Prefix.ValueString(),
		NoAAAARecords:        opnsense.BoolToString(m.NoAAAARecords.ValueBool()),
		RegisterDHCP:         opnsense.BoolToString(m.RegisterDHCP.ValueBool()),
		RegisterDHCPDomain:   m.RegisterDHCPDomain.ValueString(),
		RegisterDHCPStatic:   opnsense.BoolToString(m.RegisterDHCPStatic.ValueBool()),
		NoRegisterLinkLocal6: opnsense.BoolToString(m.NoRegisterLinkLocal6.ValueBool()),
		NoRegisterRecords:    opnsense.BoolToString(m.NoRegisterRecords.ValueBool()),
		TXTSupport:           opnsense.BoolToString(m.TXTSupport.ValueBool()),
		CacheFlush:           opnsense.BoolToString(m.CacheFlush.ValueBool()),
		LocalZoneType:        m.LocalZoneType.ValueString(),
		OutgoingInterface:    tfconv.SetToCSV(ctx, m.OutgoingInterface),
		EnableWPAD:           opnsense.BoolToString(m.EnableWPAD.ValueBool()),
	}
}

func (m *GeneralResourceModel) fromAPI(_ context.Context, a *generalAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Enabled = types.BoolValue(opnsense.StringToBool(a.Enabled))
	m.Port = types.StringValue(a.Port)
	m.Stats = types.BoolValue(opnsense.StringToBool(a.Stats))
	m.ActiveInterface = tfconv.SliceToSet(a.ActiveInterface)
	m.DNSSEC = types.BoolValue(opnsense.StringToBool(a.DNSSEC))
	m.DNS64 = types.BoolValue(opnsense.StringToBool(a.DNS64))
	m.DNS64Prefix = types.StringValue(a.DNS64Prefix)
	m.NoAAAARecords = types.BoolValue(opnsense.StringToBool(a.NoAAAARecords))
	m.RegisterDHCP = types.BoolValue(opnsense.StringToBool(a.RegisterDHCP))
	m.RegisterDHCPDomain = types.StringValue(a.RegisterDHCPDomain)
	m.RegisterDHCPStatic = types.BoolValue(opnsense.StringToBool(a.RegisterDHCPStatic))
	m.NoRegisterLinkLocal6 = types.BoolValue(opnsense.StringToBool(a.NoRegisterLinkLocal6))
	m.NoRegisterRecords = types.BoolValue(opnsense.StringToBool(a.NoRegisterRecords))
	m.TXTSupport = types.BoolValue(opnsense.StringToBool(a.TXTSupport))
	m.CacheFlush = types.BoolValue(opnsense.StringToBool(a.CacheFlush))
	m.LocalZoneType = types.StringValue(string(a.LocalZoneType))
	m.OutgoingInterface = tfconv.SliceToSet(a.OutgoingInterface)
	m.EnableWPAD = types.BoolValue(opnsense.StringToBool(a.EnableWPAD))
}
