// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package unbound

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *generalResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages the Unbound DNS general settings on OPNsense.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource identifier.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"enabled":                 schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(true), MarkdownDescription: "Enable the Unbound DNS resolver."},
			"port":                    schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Port the resolver listens on.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"stats":                   schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Collect query statistics."},
			"active_interface":        schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, MarkdownDescription: "Interfaces the resolver listens on (empty = all)."},
			"dnssec":                  schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(true), MarkdownDescription: "Enable DNSSEC validation."},
			"dns64":                   schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Enable DNS64 synthesis."},
			"dns64_prefix":            schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "DNS64 prefix (empty = well-known 64:ff9b::/96).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"no_aaaa_records":         schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Strip AAAA records from responses."},
			"register_dhcp":           schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Register DHCP leases in the resolver."},
			"register_dhcp_domain":    schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Domain appended to registered DHCP names.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"register_dhcp_static":    schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Register static DHCP mappings in the resolver."},
			"no_register_link_local6": schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Do not register IPv6 link-local addresses."},
			"no_register_records":     schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Do not register system A/AAAA records."},
			"txt_support":             schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Serve TXT records for registered hosts."},
			"cache_flush":             schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Flush the DNS cache on reconfigure."},
			"local_zone_type":         schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Local zone type (transparent, always_nxdomain, always_refuse, always_transparent, deny).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"outgoing_interface":      schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, MarkdownDescription: "Interfaces used for outgoing queries (empty = all)."},
			"enable_wpad":             schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Serve WPAD records for proxy auto-discovery."},
		},
	}
}
