// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package dnsmasq

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *bootResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a Dnsmasq DHCP boot entry on OPNsense.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource identifier.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"interface":   schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Interface this boot entry applies to; blank means any allowed interface.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"tag":         schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, MarkdownDescription: "Tags this boot entry matches."},
			"filename":    schema.StringAttribute{Required: true, MarkdownDescription: "Boot filename served to matching clients."},
			"server_name": schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Boot server name.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"address":     schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Boot server address.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"description": schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Description for this DHCP boot entry.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}
