// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package dnsmasq

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &domainDataSource{}

type domainDataSource struct{ client *opnsense.Client }

func newDomainDataSource() datasource.DataSource { return &domainDataSource{} }

func (d *domainDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dnsmasq_domain"
}

func (d *domainDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Reads a Dnsmasq domain override on OPNsense by its UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID to look up.",
			},
			"sequence":    dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Sequence number for ordering domain overrides."},
			"domain":      dsschema.StringAttribute{Computed: true, MarkdownDescription: "Domain name to override."},
			"ipset":       dsschema.StringAttribute{Computed: true, MarkdownDescription: "Firewall alias/IP set relation for this domain override."},
			"source_ip":   dsschema.StringAttribute{Computed: true, MarkdownDescription: "Optional source IP constraint."},
			"port":        dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Optional DNS server port."},
			"ip":          dsschema.StringAttribute{Computed: true, MarkdownDescription: "IP address or upstream server for this domain override."},
			"description": dsschema.StringAttribute{Computed: true, MarkdownDescription: "Description for this domain override."},
		},
	}
}

func (d *domainDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *domainDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config DomainResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[domainAPIResponse](ctx, d.client, domainReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a Dnsmasq domain override", fmt.Sprintf("Could not read a Dnsmasq domain override %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
