// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package dnsmasq

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

func (r *domainResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a Dnsmasq domain override on OPNsense.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource identifier.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"sequence":    schema.Int64Attribute{Optional: true, Computed: true, MarkdownDescription: "Sequence number for ordering domain overrides.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"domain":      schema.StringAttribute{Required: true, MarkdownDescription: "Domain name to override."},
			"ipset":       schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Firewall alias/IP set relation for this domain override.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"source_ip":   schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Optional source IP constraint.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"port":        schema.Int64Attribute{Optional: true, Computed: true, MarkdownDescription: "Optional DNS server port.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"ip":          schema.StringAttribute{Required: true, MarkdownDescription: "IP address or upstream server for this domain override."},
			"description": schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Description for this domain override.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}
