// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package dnsmasq

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/tfconv"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// DomainResourceModel is the Terraform state model for opnsense_dnsmasq_domain.
type DomainResourceModel struct {
	ID          types.String `tfsdk:"id"`
	Sequence    types.Int64  `tfsdk:"sequence"`
	Domain      types.String `tfsdk:"domain"`
	IPSet       types.String `tfsdk:"ipset"`
	SourceIP    types.String `tfsdk:"source_ip"`
	Port        types.Int64  `tfsdk:"port"`
	IP          types.String `tfsdk:"ip"`
	Description types.String `tfsdk:"description"`
}

type domainAPIResponse struct {
	Sequence    string               `json:"sequence"`
	Domain      string               `json:"domain"`
	IPSet       opnsense.SelectedMap `json:"ipset"`
	SourceIP    string               `json:"srcip"`
	Port        string               `json:"port"`
	IP          string               `json:"ip"`
	Description string               `json:"descr"`
}

type domainAPIRequest struct {
	Sequence    string `json:"sequence,omitempty"`
	Domain      string `json:"domain"`
	IPSet       string `json:"ipset,omitempty"`
	SourceIP    string `json:"srcip,omitempty"`
	Port        string `json:"port,omitempty"`
	IP          string `json:"ip"`
	Description string `json:"descr,omitempty"`
}

func (m *DomainResourceModel) toAPI(_ context.Context) *domainAPIRequest {
	return &domainAPIRequest{
		Sequence:    tfconv.IntOrEmpty(m.Sequence.ValueInt64()),
		Domain:      m.Domain.ValueString(),
		IPSet:       m.IPSet.ValueString(),
		SourceIP:    m.SourceIP.ValueString(),
		Port:        tfconv.IntOrEmpty(m.Port.ValueInt64()),
		IP:          m.IP.ValueString(),
		Description: m.Description.ValueString(),
	}
}

func (m *DomainResourceModel) fromAPI(_ context.Context, a *domainAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Sequence = types.Int64Value(tfconv.IntOrZero(a.Sequence))
	m.Domain = types.StringValue(a.Domain)
	m.IPSet = types.StringValue(string(a.IPSet))
	m.SourceIP = types.StringValue(a.SourceIP)
	m.Port = types.Int64Value(tfconv.IntOrZero(a.Port))
	m.IP = types.StringValue(a.IP)
	m.Description = types.StringValue(a.Description)
}
