// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package dnsmasq_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccHost_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_dnsmasq_host", opnsense.ReqOpts{GetEndpoint: "/api/dnsmasq/settings/get_host", Monad: "host"}),
		Steps: []resource.TestStep{
			{
				Config: testAccHostConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_dnsmasq_host.test", "id"),
			},
			{ResourceName: "opnsense_dnsmasq_host.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccHostConfig = `

resource "opnsense_dnsmasq_host" "test" {
  host = "host1"
  domain = "example.com"
  ip = "192.0.2.10"
}
`
