// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package dnsmasq

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &hostDataSource{}

type hostDataSource struct{ client *opnsense.Client }

func newHostDataSource() datasource.DataSource { return &hostDataSource{} }

func (d *hostDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dnsmasq_host"
}

func (d *hostDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Reads a Dnsmasq host entry on OPNsense by its UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID to look up.",
			},
			"host":        dsschema.StringAttribute{Computed: true, MarkdownDescription: "Hostname for this Dnsmasq host entry."},
			"domain":      dsschema.StringAttribute{Computed: true, MarkdownDescription: "Domain for this host entry."},
			"local":       dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Serve this host locally without forwarding."},
			"ip":          dsschema.StringAttribute{Computed: true, MarkdownDescription: "IP address or addresses for this host entry."},
			"cnames":      dsschema.StringAttribute{Computed: true, MarkdownDescription: "Canonical name aliases for this host entry."},
			"client_id":   dsschema.StringAttribute{Computed: true, MarkdownDescription: "DHCP client identifier."},
			"hwaddr":      dsschema.StringAttribute{Computed: true, MarkdownDescription: "Hardware or MAC address values."},
			"lease_time":  dsschema.Int64Attribute{Computed: true, MarkdownDescription: "DHCP lease time for this host entry."},
			"ignore":      dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Ignore DHCP requests from this host."},
			"set_tag":     dsschema.StringAttribute{Computed: true, MarkdownDescription: "DHCP tag to set for this host."},
			"description": dsschema.StringAttribute{Computed: true, MarkdownDescription: "Description for this host entry."},
			"comments":    dsschema.StringAttribute{Computed: true, MarkdownDescription: "Additional comments for this host entry."},
			"aliases":     dsschema.StringAttribute{Computed: true, MarkdownDescription: "Legacy aliases for this host entry."},
		},
	}
}

func (d *hostDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *hostDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config HostResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[hostAPIResponse](ctx, d.client, hostReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a Dnsmasq host entry", fmt.Sprintf("Could not read a Dnsmasq host entry %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
