// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package dnsmasq

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

func (r *hostResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a Dnsmasq host entry on OPNsense.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource identifier.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"host":        schema.StringAttribute{Required: true, MarkdownDescription: "Hostname for this Dnsmasq host entry."},
			"domain":      schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Domain for this host entry.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"local":       schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Serve this host locally without forwarding."},
			"ip":          schema.StringAttribute{Required: true, MarkdownDescription: "IP address or addresses for this host entry."},
			"cnames":      schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Canonical name aliases for this host entry.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"client_id":   schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "DHCP client identifier.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"hwaddr":      schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Hardware or MAC address values.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"lease_time":  schema.Int64Attribute{Optional: true, Computed: true, MarkdownDescription: "DHCP lease time for this host entry.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"ignore":      schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Ignore DHCP requests from this host."},
			"set_tag":     schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "DHCP tag to set for this host.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"description": schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Description for this host entry.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"comments":    schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Additional comments for this host entry.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"aliases":     schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Legacy aliases for this host entry.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}
