// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package dnsmasq

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/tfconv"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// OptionResourceModel is the Terraform state model for opnsense_dnsmasq_option.
type OptionResourceModel struct {
	ID          types.String `tfsdk:"id"`
	Type        types.String `tfsdk:"type"`
	Option      types.String `tfsdk:"option"`
	Option6     types.String `tfsdk:"option6"`
	Interface   types.String `tfsdk:"interface"`
	Tag         types.Set    `tfsdk:"tag"`
	SetTag      types.String `tfsdk:"set_tag"`
	Value       types.String `tfsdk:"value"`
	Force       types.Bool   `tfsdk:"force"`
	Description types.String `tfsdk:"description"`
}

type optionAPIResponse struct {
	Type        opnsense.SelectedMap     `json:"type"`
	Option      string                   `json:"option"`
	Option6     string                   `json:"option6"`
	Interface   opnsense.SelectedMap     `json:"interface"`
	Tag         opnsense.SelectedMapList `json:"tag"`
	SetTag      opnsense.SelectedMap     `json:"set_tag"`
	Value       string                   `json:"value"`
	Force       string                   `json:"force"`
	Description string                   `json:"description"`
}

type optionAPIRequest struct {
	Type        string `json:"type"`
	Option      string `json:"option,omitempty"`
	Option6     string `json:"option6,omitempty"`
	Interface   string `json:"interface,omitempty"`
	Tag         string `json:"tag,omitempty"`
	SetTag      string `json:"set_tag,omitempty"`
	Value       string `json:"value,omitempty"`
	Force       string `json:"force"`
	Description string `json:"description,omitempty"`
}

func (m *OptionResourceModel) toAPI(ctx context.Context) *optionAPIRequest {
	return &optionAPIRequest{
		Type:        m.Type.ValueString(),
		Option:      m.Option.ValueString(),
		Option6:     m.Option6.ValueString(),
		Interface:   m.Interface.ValueString(),
		Tag:         tfconv.SetToCSV(ctx, m.Tag),
		SetTag:      m.SetTag.ValueString(),
		Value:       m.Value.ValueString(),
		Force:       opnsense.BoolToString(m.Force.ValueBool()),
		Description: m.Description.ValueString(),
	}
}

func (m *OptionResourceModel) fromAPI(_ context.Context, a *optionAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Type = types.StringValue(string(a.Type))
	m.Option = types.StringValue(a.Option)
	m.Option6 = types.StringValue(a.Option6)
	m.Interface = types.StringValue(string(a.Interface))
	m.Tag = tfconv.SliceToSet(a.Tag)
	m.SetTag = types.StringValue(string(a.SetTag))
	m.Value = types.StringValue(a.Value)
	m.Force = types.BoolValue(opnsense.StringToBool(a.Force))
	m.Description = types.StringValue(a.Description)
}
