// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package dnsmasq_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccOption_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_dnsmasq_option", opnsense.ReqOpts{GetEndpoint: "/api/dnsmasq/settings/get_option", Monad: "option"}),
		Steps: []resource.TestStep{
			{
				Config: testAccOptionConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_dnsmasq_option.test", "id"),
			},
			{ResourceName: "opnsense_dnsmasq_option.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccOptionConfig = `

resource "opnsense_dnsmasq_option" "test" {
  type = "set"
  option = "66"
  value = "192.0.2.20"
}
`
