// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package dnsmasq

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *optionResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a Dnsmasq DHCP option on OPNsense.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource identifier.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"type":        schema.StringAttribute{Required: true, MarkdownDescription: "DHCP option type.", Validators: []validator.String{stringvalidator.OneOf("set", "match")}},
			"option":      schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "IPv4 DHCP option key.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"option6":     schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "IPv6 DHCP option key.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"interface":   schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Interface this option applies to; blank means any allowed interface.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"tag":         schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, MarkdownDescription: "Tags this option matches."},
			"set_tag":     schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Tag to set when this option matches.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"value":       schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "DHCP option value.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"force":       schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Force this option even if a client did not request it."},
			"description": schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Description for this DHCP option.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}
