// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package dnsmasq

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &optionDataSource{}

type optionDataSource struct{ client *opnsense.Client }

func newOptionDataSource() datasource.DataSource { return &optionDataSource{} }

func (d *optionDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dnsmasq_option"
}

func (d *optionDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Reads a Dnsmasq DHCP option on OPNsense by its UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID to look up.",
			},
			"type":        dsschema.StringAttribute{Computed: true, MarkdownDescription: "DHCP option type."},
			"option":      dsschema.StringAttribute{Computed: true, MarkdownDescription: "IPv4 DHCP option key."},
			"option6":     dsschema.StringAttribute{Computed: true, MarkdownDescription: "IPv6 DHCP option key."},
			"interface":   dsschema.StringAttribute{Computed: true, MarkdownDescription: "Interface this option applies to; blank means any allowed interface."},
			"tag":         dsschema.SetAttribute{ElementType: types.StringType, Computed: true, MarkdownDescription: "Tags this option matches."},
			"set_tag":     dsschema.StringAttribute{Computed: true, MarkdownDescription: "Tag to set when this option matches."},
			"value":       dsschema.StringAttribute{Computed: true, MarkdownDescription: "DHCP option value."},
			"force":       dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Force this option even if a client did not request it."},
			"description": dsschema.StringAttribute{Computed: true, MarkdownDescription: "Description for this DHCP option."},
		},
	}
}

func (d *optionDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *optionDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config OptionResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[optionAPIResponse](ctx, d.client, optionReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a Dnsmasq DHCP option", fmt.Sprintf("Could not read a Dnsmasq DHCP option %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
