// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package dnsmasq

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &rangeDataSource{}

type rangeDataSource struct{ client *opnsense.Client }

func newRangeDataSource() datasource.DataSource { return &rangeDataSource{} }

func (d *rangeDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dnsmasq_range"
}

func (d *rangeDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Reads a Dnsmasq DHCP range on OPNsense by its UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID to look up.",
			},
			"interface":          dsschema.StringAttribute{Computed: true, MarkdownDescription: "Interface this DHCP range applies to; blank means any allowed interface."},
			"set_tag":            dsschema.StringAttribute{Computed: true, MarkdownDescription: "DHCP tag to set for leases in this range."},
			"start_address":      dsschema.StringAttribute{Computed: true, MarkdownDescription: "Start address for this DHCP range."},
			"end_address":        dsschema.StringAttribute{Computed: true, MarkdownDescription: "End address for this DHCP range."},
			"subnet_mask":        dsschema.StringAttribute{Computed: true, MarkdownDescription: "IPv4 subnet mask for this DHCP range."},
			"constructor":        dsschema.StringAttribute{Computed: true, MarkdownDescription: "Interface constructor for dynamic range generation."},
			"mode":               dsschema.SetAttribute{ElementType: types.StringType, Computed: true, MarkdownDescription: "Range mode flags."},
			"prefix_length":      dsschema.Int64Attribute{Computed: true, MarkdownDescription: "IPv6 prefix length for this range."},
			"lease_time":         dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Lease time for this DHCP range."},
			"domain_type":        dsschema.StringAttribute{Computed: true, MarkdownDescription: "How the DHCP domain is derived."},
			"domain":             dsschema.StringAttribute{Computed: true, MarkdownDescription: "Domain for this DHCP range."},
			"no_sync":            dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Exclude this range from HA synchronization."},
			"ra_mode":            dsschema.SetAttribute{ElementType: types.StringType, Computed: true, MarkdownDescription: "IPv6 router advertisement modes."},
			"ra_priority":        dsschema.StringAttribute{Computed: true, MarkdownDescription: "Router advertisement priority."},
			"ra_mtu":             dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Router advertisement MTU."},
			"ra_interval":        dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Router advertisement interval."},
			"ra_router_lifetime": dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Router advertisement router lifetime."},
			"description":        dsschema.StringAttribute{Computed: true, MarkdownDescription: "Description for this DHCP range."},
		},
	}
}

func (d *rangeDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *rangeDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config RangeResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[rangeAPIResponse](ctx, d.client, rangeReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a Dnsmasq DHCP range", fmt.Sprintf("Could not read a Dnsmasq DHCP range %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
