// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package dnsmasq_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccRange_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_dnsmasq_range", opnsense.ReqOpts{GetEndpoint: "/api/dnsmasq/settings/get_range", Monad: "range"}),
		Steps: []resource.TestStep{
			{
				Config: testAccRangeConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_dnsmasq_range.test", "id"),
			},
			{ResourceName: "opnsense_dnsmasq_range.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccRangeConfig = `

resource "opnsense_dnsmasq_range" "test" {
  start_address = "192.0.2.100"
  end_address = "192.0.2.150"
  domain_type = "range"
}
`
