// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package dnsmasq

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *settingsResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages the Dnsmasq DNS/DHCP general settings on OPNsense.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource identifier.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"enable":               schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Enable the Dnsmasq service."},
			"register_dhcp":        schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Register DHCP leases in DNS."},
			"register_dhcp_static": schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Register static DHCP mappings in DNS."},
			"dhcp_first":           schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Prefer DHCP names over other sources."},
			"strict_order":         schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Query upstream servers in strict order."},
			"domain_needed":        schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Never forward queries without a domain."},
			"no_private_reverse":   schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Do not forward reverse lookups for private ranges."},
			"no_resolv":            schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Ignore /etc/resolv.conf for upstream servers."},
			"log_queries":          schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Log all DNS queries."},
			"no_hosts":             schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Do not read /etc/hosts."},
			"strict_bind":          schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Bind only to configured interfaces."},
			"dnssec":               schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Enable DNSSEC validation."},
			"register_dhcp_domain": schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Domain appended to registered DHCP names.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"interface":            schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, MarkdownDescription: "Interfaces Dnsmasq listens on (empty = all)."},
			"port":                 schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Service listen port (empty = default).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"dns_port":             schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "DNS listen port.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"dns_forward_max":      schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Maximum concurrent forwarded queries.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"cache_size":           schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "DNS cache size (entries).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"local_ttl":            schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "TTL for locally-served records.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"add_mac":              schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Add requesting MAC to forwarded queries (standard, base64, text).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"add_subnet":           schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Add the client subnet to forwarded queries."},
			"strip_subnet":         schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Strip the client subnet from replies."},
			"dhcp":                 schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, MarkdownDescription: "DHCP behaviour flags."},
			"no_ident":             schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(true), MarkdownDescription: "Disable the chaos TXT ident responses."},
		},
	}
}
