// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package dnsmasq_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
)

func TestAccSettings_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		Steps: []resource.TestStep{
			{
				Config: testAccSettingsConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_dnsmasq_settings.test", "id"),
			},
			{ResourceName: "opnsense_dnsmasq_settings.test", ImportState: true, ImportStateId: "dnsmasq", ImportStateVerify: true},
		},
	})
}

const testAccSettingsConfig = `

resource "opnsense_dnsmasq_settings" "test" {
}
`
