// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package dnsmasq

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/tfconv"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// SettingsResourceModel is the Terraform state model for opnsense_dnsmasq_settings.
type SettingsResourceModel struct {
	ID                 types.String `tfsdk:"id"`
	Enable             types.Bool   `tfsdk:"enable"`
	RegisterDHCP       types.Bool   `tfsdk:"register_dhcp"`
	RegisterDHCPStatic types.Bool   `tfsdk:"register_dhcp_static"`
	DHCPFirst          types.Bool   `tfsdk:"dhcp_first"`
	StrictOrder        types.Bool   `tfsdk:"strict_order"`
	DomainNeeded       types.Bool   `tfsdk:"domain_needed"`
	NoPrivateReverse   types.Bool   `tfsdk:"no_private_reverse"`
	NoResolv           types.Bool   `tfsdk:"no_resolv"`
	LogQueries         types.Bool   `tfsdk:"log_queries"`
	NoHosts            types.Bool   `tfsdk:"no_hosts"`
	StrictBind         types.Bool   `tfsdk:"strict_bind"`
	DNSSEC             types.Bool   `tfsdk:"dnssec"`
	RegisterDHCPDomain types.String `tfsdk:"register_dhcp_domain"`
	Interface          types.Set    `tfsdk:"interface"`
	Port               types.String `tfsdk:"port"`
	DNSPort            types.String `tfsdk:"dns_port"`
	DNSForwardMax      types.String `tfsdk:"dns_forward_max"`
	CacheSize          types.String `tfsdk:"cache_size"`
	LocalTTL           types.String `tfsdk:"local_ttl"`
	AddMAC             types.String `tfsdk:"add_mac"`
	AddSubnet          types.Bool   `tfsdk:"add_subnet"`
	StripSubnet        types.Bool   `tfsdk:"strip_subnet"`
	DHCP               types.Set    `tfsdk:"dhcp"`
	NoIdent            types.Bool   `tfsdk:"no_ident"`
}

type settingsAPIResponse struct {
	Enable             string                   `json:"enable"`
	RegisterDHCP       string                   `json:"regdhcp"`
	RegisterDHCPStatic string                   `json:"regdhcpstatic"`
	DHCPFirst          string                   `json:"dhcpfirst"`
	StrictOrder        string                   `json:"strict_order"`
	DomainNeeded       string                   `json:"domain_needed"`
	NoPrivateReverse   string                   `json:"no_private_reverse"`
	NoResolv           string                   `json:"no_resolv"`
	LogQueries         string                   `json:"log_queries"`
	NoHosts            string                   `json:"no_hosts"`
	StrictBind         string                   `json:"strictbind"`
	DNSSEC             string                   `json:"dnssec"`
	RegisterDHCPDomain string                   `json:"regdhcpdomain"`
	Interface          opnsense.SelectedMapList `json:"interface"`
	Port               string                   `json:"port"`
	DNSPort            string                   `json:"dns_port"`
	DNSForwardMax      string                   `json:"dns_forward_max"`
	CacheSize          string                   `json:"cache_size"`
	LocalTTL           string                   `json:"local_ttl"`
	AddMAC             opnsense.SelectedMap     `json:"add_mac"`
	AddSubnet          string                   `json:"add_subnet"`
	StripSubnet        string                   `json:"strip_subnet"`
	DHCP               opnsense.SelectedMapList `json:"dhcp"`
	NoIdent            string                   `json:"no_ident"`
}

type settingsAPIRequest struct {
	Enable             string `json:"enable"`
	RegisterDHCP       string `json:"regdhcp"`
	RegisterDHCPStatic string `json:"regdhcpstatic"`
	DHCPFirst          string `json:"dhcpfirst"`
	StrictOrder        string `json:"strict_order"`
	DomainNeeded       string `json:"domain_needed"`
	NoPrivateReverse   string `json:"no_private_reverse"`
	NoResolv           string `json:"no_resolv"`
	LogQueries         string `json:"log_queries"`
	NoHosts            string `json:"no_hosts"`
	StrictBind         string `json:"strictbind"`
	DNSSEC             string `json:"dnssec"`
	RegisterDHCPDomain string `json:"regdhcpdomain,omitempty"`
	Interface          string `json:"interface,omitempty"`
	Port               string `json:"port,omitempty"`
	DNSPort            string `json:"dns_port,omitempty"`
	DNSForwardMax      string `json:"dns_forward_max,omitempty"`
	CacheSize          string `json:"cache_size,omitempty"`
	LocalTTL           string `json:"local_ttl,omitempty"`
	AddMAC             string `json:"add_mac,omitempty"`
	AddSubnet          string `json:"add_subnet"`
	StripSubnet        string `json:"strip_subnet"`
	DHCP               string `json:"dhcp,omitempty"`
	NoIdent            string `json:"no_ident"`
}

func (m *SettingsResourceModel) toAPI(ctx context.Context) *settingsAPIRequest {
	return &settingsAPIRequest{
		Enable:             opnsense.BoolToString(m.Enable.ValueBool()),
		RegisterDHCP:       opnsense.BoolToString(m.RegisterDHCP.ValueBool()),
		RegisterDHCPStatic: opnsense.BoolToString(m.RegisterDHCPStatic.ValueBool()),
		DHCPFirst:          opnsense.BoolToString(m.DHCPFirst.ValueBool()),
		StrictOrder:        opnsense.BoolToString(m.StrictOrder.ValueBool()),
		DomainNeeded:       opnsense.BoolToString(m.DomainNeeded.ValueBool()),
		NoPrivateReverse:   opnsense.BoolToString(m.NoPrivateReverse.ValueBool()),
		NoResolv:           opnsense.BoolToString(m.NoResolv.ValueBool()),
		LogQueries:         opnsense.BoolToString(m.LogQueries.ValueBool()),
		NoHosts:            opnsense.BoolToString(m.NoHosts.ValueBool()),
		StrictBind:         opnsense.BoolToString(m.StrictBind.ValueBool()),
		DNSSEC:             opnsense.BoolToString(m.DNSSEC.ValueBool()),
		RegisterDHCPDomain: m.RegisterDHCPDomain.ValueString(),
		Interface:          tfconv.SetToCSV(ctx, m.Interface),
		Port:               m.Port.ValueString(),
		DNSPort:            m.DNSPort.ValueString(),
		DNSForwardMax:      m.DNSForwardMax.ValueString(),
		CacheSize:          m.CacheSize.ValueString(),
		LocalTTL:           m.LocalTTL.ValueString(),
		AddMAC:             m.AddMAC.ValueString(),
		AddSubnet:          opnsense.BoolToString(m.AddSubnet.ValueBool()),
		StripSubnet:        opnsense.BoolToString(m.StripSubnet.ValueBool()),
		DHCP:               tfconv.SetToCSV(ctx, m.DHCP),
		NoIdent:            opnsense.BoolToString(m.NoIdent.ValueBool()),
	}
}

func (m *SettingsResourceModel) fromAPI(_ context.Context, a *settingsAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Enable = types.BoolValue(opnsense.StringToBool(a.Enable))
	m.RegisterDHCP = types.BoolValue(opnsense.StringToBool(a.RegisterDHCP))
	m.RegisterDHCPStatic = types.BoolValue(opnsense.StringToBool(a.RegisterDHCPStatic))
	m.DHCPFirst = types.BoolValue(opnsense.StringToBool(a.DHCPFirst))
	m.StrictOrder = types.BoolValue(opnsense.StringToBool(a.StrictOrder))
	m.DomainNeeded = types.BoolValue(opnsense.StringToBool(a.DomainNeeded))
	m.NoPrivateReverse = types.BoolValue(opnsense.StringToBool(a.NoPrivateReverse))
	m.NoResolv = types.BoolValue(opnsense.StringToBool(a.NoResolv))
	m.LogQueries = types.BoolValue(opnsense.StringToBool(a.LogQueries))
	m.NoHosts = types.BoolValue(opnsense.StringToBool(a.NoHosts))
	m.StrictBind = types.BoolValue(opnsense.StringToBool(a.StrictBind))
	m.DNSSEC = types.BoolValue(opnsense.StringToBool(a.DNSSEC))
	m.RegisterDHCPDomain = types.StringValue(a.RegisterDHCPDomain)
	m.Interface = tfconv.SliceToSet(a.Interface)
	m.Port = types.StringValue(a.Port)
	m.DNSPort = types.StringValue(a.DNSPort)
	m.DNSForwardMax = types.StringValue(a.DNSForwardMax)
	m.CacheSize = types.StringValue(a.CacheSize)
	m.LocalTTL = types.StringValue(a.LocalTTL)
	m.AddMAC = types.StringValue(string(a.AddMAC))
	m.AddSubnet = types.BoolValue(opnsense.StringToBool(a.AddSubnet))
	m.StripSubnet = types.BoolValue(opnsense.StringToBool(a.StripSubnet))
	m.DHCP = tfconv.SliceToSet(a.DHCP)
	m.NoIdent = types.BoolValue(opnsense.StringToBool(a.NoIdent))
}
