// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package trafficshaper

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/tfconv"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// PipeResourceModel is the Terraform state model for opnsense_trafficshaper_pipe.
type PipeResourceModel struct {
	ID              types.String `tfsdk:"id"`
	Enabled         types.Bool   `tfsdk:"enabled"`
	Number          types.Int64  `tfsdk:"number"`
	Bandwidth       types.Int64  `tfsdk:"bandwidth"`
	BandwidthMetric types.String `tfsdk:"bandwidth_metric"`
	Mask            types.String `tfsdk:"mask"`
	Scheduler       types.String `tfsdk:"scheduler"`
	Description     types.String `tfsdk:"description"`
}

type pipeAPIResponse struct {
	Enabled         string               `json:"enabled"`
	Number          string               `json:"number"`
	Bandwidth       string               `json:"bandwidth"`
	BandwidthMetric opnsense.SelectedMap `json:"bandwidthMetric"`
	Mask            opnsense.SelectedMap `json:"mask"`
	Scheduler       opnsense.SelectedMap `json:"scheduler"`
	Description     string               `json:"description"`
}

type pipeAPIRequest struct {
	Enabled         string `json:"enabled"`
	Number          string `json:"number,omitempty"`
	Bandwidth       string `json:"bandwidth"`
	BandwidthMetric string `json:"bandwidthMetric"`
	Mask            string `json:"mask,omitempty"`
	Scheduler       string `json:"scheduler,omitempty"`
	Description     string `json:"description,omitempty"`
}

func (m *PipeResourceModel) toAPI(_ context.Context) *pipeAPIRequest {
	return &pipeAPIRequest{
		Enabled:         opnsense.BoolToString(m.Enabled.ValueBool()),
		Number:          tfconv.IntOrEmpty(m.Number.ValueInt64()),
		Bandwidth:       opnsense.Int64ToString(m.Bandwidth.ValueInt64()),
		BandwidthMetric: m.BandwidthMetric.ValueString(),
		Mask:            m.Mask.ValueString(),
		Scheduler:       m.Scheduler.ValueString(),
		Description:     m.Description.ValueString(),
	}
}

func (m *PipeResourceModel) fromAPI(_ context.Context, a *pipeAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Enabled = types.BoolValue(opnsense.StringToBool(a.Enabled))
	m.Number = types.Int64Value(tfconv.IntOrZero(a.Number))
	m.Bandwidth = types.Int64Value(tfconv.IntOrZero(a.Bandwidth))
	m.BandwidthMetric = types.StringValue(string(a.BandwidthMetric))
	m.Mask = types.StringValue(string(a.Mask))
	m.Scheduler = types.StringValue(string(a.Scheduler))
	m.Description = types.StringValue(a.Description)
}
