// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package trafficshaper

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &pipeDataSource{}

type pipeDataSource struct{ client *opnsense.Client }

func newPipeDataSource() datasource.DataSource { return &pipeDataSource{} }

func (d *pipeDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_trafficshaper_pipe"
}

func (d *pipeDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Reads a traffic shaper pipe on OPNsense by its UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID to look up.",
			},
			"enabled":          dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether this pipe is enabled."},
			"number":           dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Pipe number (auto-assigned by OPNsense)."},
			"bandwidth":        dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Bandwidth value."},
			"bandwidth_metric": dsschema.StringAttribute{Computed: true, MarkdownDescription: "Bandwidth unit: bit, Kbit, Mbit, Gbit."},
			"mask":             dsschema.StringAttribute{Computed: true, MarkdownDescription: "Dynamic pipe mask: none, src-ip, dst-ip."},
			"scheduler":        dsschema.StringAttribute{Computed: true, MarkdownDescription: "Scheduler type (e.g. fq_codel)."},
			"description":      dsschema.StringAttribute{Computed: true, MarkdownDescription: "Description (required by OPNsense)."},
		},
	}
}

func (d *pipeDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *pipeDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config PipeResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[pipeAPIResponse](ctx, d.client, pipeReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a traffic shaper pipe", fmt.Sprintf("Could not read a traffic shaper pipe %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
