// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package trafficshaper_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccPipe_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_trafficshaper_pipe", opnsense.ReqOpts{GetEndpoint: "/api/trafficshaper/settings/get_pipe", Monad: "pipe"}),
		Steps: []resource.TestStep{
			{
				Config: testAccPipeConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_trafficshaper_pipe.test", "id"),
			},
			{ResourceName: "opnsense_trafficshaper_pipe.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccPipeConfig = `
resource "opnsense_trafficshaper_pipe" "test" {
  number = 1
  bandwidth = 1
  bandwidth_metric = "Mbit"
  description = "tf-acc-pipe"
}
`
