// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package trafficshaper_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccQueue_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_trafficshaper_queue", opnsense.ReqOpts{GetEndpoint: "/api/trafficshaper/settings/get_queue", Monad: "queue"}),
		Steps: []resource.TestStep{
			{
				Config: testAccQueueConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_trafficshaper_queue.test", "id"),
			},
			{ResourceName: "opnsense_trafficshaper_queue.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccQueueConfig = `
resource "opnsense_trafficshaper_queue" "test" {
  number = 1
  pipe = "test"
  weight = 1
}
`
