// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package trafficshaper

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/tfconv"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// QueueResourceModel is the Terraform state model for opnsense_trafficshaper_queue.
type QueueResourceModel struct {
	ID          types.String `tfsdk:"id"`
	Enabled     types.Bool   `tfsdk:"enabled"`
	Number      types.Int64  `tfsdk:"number"`
	Pipe        types.String `tfsdk:"pipe"`
	Weight      types.Int64  `tfsdk:"weight"`
	Mask        types.String `tfsdk:"mask"`
	Description types.String `tfsdk:"description"`
}

type queueAPIResponse struct {
	Enabled     string               `json:"enabled"`
	Number      string               `json:"number"`
	Pipe        opnsense.SelectedMap `json:"pipe"`
	Weight      string               `json:"weight"`
	Mask        opnsense.SelectedMap `json:"mask"`
	Description string               `json:"description"`
}

type queueAPIRequest struct {
	Enabled     string `json:"enabled"`
	Number      string `json:"number"`
	Pipe        string `json:"pipe"`
	Weight      string `json:"weight"`
	Mask        string `json:"mask,omitempty"`
	Description string `json:"description,omitempty"`
}

func (m *QueueResourceModel) toAPI(_ context.Context) *queueAPIRequest {
	return &queueAPIRequest{
		Enabled:     opnsense.BoolToString(m.Enabled.ValueBool()),
		Number:      opnsense.Int64ToString(m.Number.ValueInt64()),
		Pipe:        m.Pipe.ValueString(),
		Weight:      opnsense.Int64ToString(m.Weight.ValueInt64()),
		Mask:        m.Mask.ValueString(),
		Description: m.Description.ValueString(),
	}
}

func (m *QueueResourceModel) fromAPI(_ context.Context, a *queueAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Enabled = types.BoolValue(opnsense.StringToBool(a.Enabled))
	m.Number = types.Int64Value(tfconv.IntOrZero(a.Number))
	m.Pipe = types.StringValue(string(a.Pipe))
	m.Weight = types.Int64Value(tfconv.IntOrZero(a.Weight))
	m.Mask = types.StringValue(string(a.Mask))
	m.Description = types.StringValue(a.Description)
}
