// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package trafficshaper

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &queueDataSource{}

type queueDataSource struct{ client *opnsense.Client }

func newQueueDataSource() datasource.DataSource { return &queueDataSource{} }

func (d *queueDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_trafficshaper_queue"
}

func (d *queueDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Reads a traffic shaper queue on OPNsense by its UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID to look up.",
			},
			"enabled":     dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether this queue is enabled."},
			"number":      dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Queue number (auto-assigned by OPNsense)."},
			"pipe":        dsschema.StringAttribute{Computed: true, MarkdownDescription: "UUID of the parent pipe."},
			"weight":      dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Queue weight (1-100)."},
			"mask":        dsschema.StringAttribute{Computed: true, MarkdownDescription: "Dynamic queue mask: none, src-ip, dst-ip."},
			"description": dsschema.StringAttribute{Computed: true, MarkdownDescription: "Description."},
		},
	}
}

func (d *queueDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *queueDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config QueueResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[queueAPIResponse](ctx, d.client, queueReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a traffic shaper queue", fmt.Sprintf("Could not read a traffic shaper queue %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
