// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package trafficshaper

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &ruleDataSource{}

type ruleDataSource struct{ client *opnsense.Client }

func newRuleDataSource() datasource.DataSource { return &ruleDataSource{} }

func (d *ruleDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_trafficshaper_rule"
}

func (d *ruleDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Reads a traffic shaper rule on OPNsense by its UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID to look up.",
			},
			"enabled":          dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether this rule is enabled."},
			"sequence":         dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Rule evaluation order."},
			"interface":        dsschema.StringAttribute{Computed: true, MarkdownDescription: "Interface to match."},
			"protocol":         dsschema.StringAttribute{Computed: true, MarkdownDescription: "Protocol to match (e.g. ip, tcp, udp)."},
			"source":           dsschema.StringAttribute{Computed: true, MarkdownDescription: "Source network/host."},
			"source_not":       dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Invert the source match."},
			"source_port":      dsschema.StringAttribute{Computed: true, MarkdownDescription: "Source port (empty = any)."},
			"destination":      dsschema.StringAttribute{Computed: true, MarkdownDescription: "Destination network/host."},
			"destination_not":  dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Invert the destination match."},
			"destination_port": dsschema.StringAttribute{Computed: true, MarkdownDescription: "Destination port (empty = any)."},
			"direction":        dsschema.StringAttribute{Computed: true, MarkdownDescription: "Traffic direction (empty = both)."},
			"target":           dsschema.StringAttribute{Computed: true, MarkdownDescription: "UUID of the target pipe or queue."},
			"description":      dsschema.StringAttribute{Computed: true, MarkdownDescription: "Description."},
		},
	}
}

func (d *ruleDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *ruleDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config RuleResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[ruleAPIResponse](ctx, d.client, ruleReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a traffic shaper rule", fmt.Sprintf("Could not read a traffic shaper rule %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
