// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package trafficshaper

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

func (r *ruleResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a traffic shaper rule on OPNsense.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource identifier.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"enabled":          schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(true), MarkdownDescription: "Whether this rule is enabled."},
			"sequence":         schema.Int64Attribute{Required: true, MarkdownDescription: "Rule evaluation order."},
			"interface":        schema.StringAttribute{Required: true, MarkdownDescription: "Interface to match."},
			"protocol":         schema.StringAttribute{Required: true, MarkdownDescription: "Protocol to match (e.g. ip, tcp, udp)."},
			"source":           schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Source network/host.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"source_not":       schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Invert the source match."},
			"source_port":      schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Source port (empty = any).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"destination":      schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Destination network/host.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"destination_not":  schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Invert the destination match."},
			"destination_port": schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Destination port (empty = any).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"direction":        schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Traffic direction (empty = both).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"target":           schema.StringAttribute{Required: true, MarkdownDescription: "UUID of the target pipe or queue."},
			"description":      schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Description.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}
