// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package trafficshaper_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccRule_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_trafficshaper_rule", opnsense.ReqOpts{GetEndpoint: "/api/trafficshaper/settings/get_rule", Monad: "rule"}),
		Steps: []resource.TestStep{
			{
				Config: testAccRuleConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_trafficshaper_rule.test", "id"),
			},
			{ResourceName: "opnsense_trafficshaper_rule.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccRuleConfig = `
resource "opnsense_trafficshaper_pipe" "prereq" {
  bandwidth        = 10
  bandwidth_metric = "Mbit"
  description      = "tf-acc-rule-pipe"
}

resource "opnsense_trafficshaper_rule" "test" {
  sequence = 1
  interface = "lan"
  protocol = "ip"
  source_port = "any"
  destination_port = "any"
  target = opnsense_trafficshaper_pipe.prereq.id
  description = "tf-acc-rule"
}
`
