// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package trafficshaper

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/tfconv"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// RuleResourceModel is the Terraform state model for opnsense_trafficshaper_rule.
type RuleResourceModel struct {
	ID              types.String `tfsdk:"id"`
	Enabled         types.Bool   `tfsdk:"enabled"`
	Sequence        types.Int64  `tfsdk:"sequence"`
	Interface       types.String `tfsdk:"interface"`
	Protocol        types.String `tfsdk:"protocol"`
	Source          types.String `tfsdk:"source"`
	SourceNot       types.Bool   `tfsdk:"source_not"`
	SourcePort      types.String `tfsdk:"source_port"`
	Destination     types.String `tfsdk:"destination"`
	DestinationNot  types.Bool   `tfsdk:"destination_not"`
	DestinationPort types.String `tfsdk:"destination_port"`
	Direction       types.String `tfsdk:"direction"`
	Target          types.String `tfsdk:"target"`
	Description     types.String `tfsdk:"description"`
}

type ruleAPIResponse struct {
	Enabled         string               `json:"enabled"`
	Sequence        string               `json:"sequence"`
	Interface       opnsense.SelectedMap `json:"interface"`
	Protocol        opnsense.SelectedMap `json:"proto"`
	Source          string               `json:"source"`
	SourceNot       string               `json:"source_not"`
	SourcePort      string               `json:"src_port"`
	Destination     string               `json:"destination"`
	DestinationNot  string               `json:"destination_not"`
	DestinationPort string               `json:"dst_port"`
	Direction       opnsense.SelectedMap `json:"direction"`
	Target          opnsense.SelectedMap `json:"target"`
	Description     string               `json:"description"`
}

type ruleAPIRequest struct {
	Enabled         string `json:"enabled"`
	Sequence        string `json:"sequence"`
	Interface       string `json:"interface"`
	Protocol        string `json:"proto"`
	Source          string `json:"source"`
	SourceNot       string `json:"source_not"`
	SourcePort      string `json:"src_port"`
	Destination     string `json:"destination"`
	DestinationNot  string `json:"destination_not"`
	DestinationPort string `json:"dst_port"`
	Direction       string `json:"direction"`
	Target          string `json:"target"`
	Description     string `json:"description"`
}

func (m *RuleResourceModel) toAPI(_ context.Context) *ruleAPIRequest {
	return &ruleAPIRequest{
		Enabled:         opnsense.BoolToString(m.Enabled.ValueBool()),
		Sequence:        opnsense.Int64ToString(m.Sequence.ValueInt64()),
		Interface:       m.Interface.ValueString(),
		Protocol:        m.Protocol.ValueString(),
		Source:          m.Source.ValueString(),
		SourceNot:       opnsense.BoolToString(m.SourceNot.ValueBool()),
		SourcePort:      m.SourcePort.ValueString(),
		Destination:     m.Destination.ValueString(),
		DestinationNot:  opnsense.BoolToString(m.DestinationNot.ValueBool()),
		DestinationPort: m.DestinationPort.ValueString(),
		Direction:       m.Direction.ValueString(),
		Target:          m.Target.ValueString(),
		Description:     m.Description.ValueString(),
	}
}

func (m *RuleResourceModel) fromAPI(_ context.Context, a *ruleAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Enabled = types.BoolValue(opnsense.StringToBool(a.Enabled))
	m.Sequence = types.Int64Value(tfconv.IntOrZero(a.Sequence))
	m.Interface = types.StringValue(string(a.Interface))
	m.Protocol = types.StringValue(string(a.Protocol))
	m.Source = types.StringValue(a.Source)
	m.SourceNot = types.BoolValue(opnsense.StringToBool(a.SourceNot))
	m.SourcePort = types.StringValue(a.SourcePort)
	m.Destination = types.StringValue(a.Destination)
	m.DestinationNot = types.BoolValue(opnsense.StringToBool(a.DestinationNot))
	m.DestinationPort = types.StringValue(a.DestinationPort)
	m.Direction = types.StringValue(string(a.Direction))
	m.Target = types.StringValue(string(a.Target))
	m.Description = types.StringValue(a.Description)
}
