// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package auth_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccGroup_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_auth_group", opnsense.ReqOpts{GetEndpoint: "/api/auth/group/get", Monad: "group"}),
		Steps: []resource.TestStep{
			{
				Config: testAccGroupConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_auth_group.test", "id"),
			},
			{ResourceName: "opnsense_auth_group.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccGroupConfig = `
resource "opnsense_auth_group" "test" {
  name = "tfaccgroup"
}
`
