// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package auth

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &groupDataSource{}

type groupDataSource struct{ client *opnsense.Client }

func newGroupDataSource() datasource.DataSource { return &groupDataSource{} }

func (d *groupDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_auth_group"
}

func (d *groupDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Look up an existing a local group on OPNsense by UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID of the a local group to look up.",
			},
			"name":            dsschema.StringAttribute{Computed: true, MarkdownDescription: "Group name (unique)."},
			"description":     dsschema.StringAttribute{Computed: true, MarkdownDescription: "Description."},
			"privileges":      dsschema.SetAttribute{ElementType: types.StringType, Computed: true, MarkdownDescription: "Assigned privilege identifiers."},
			"members":         dsschema.SetAttribute{ElementType: types.StringType, Computed: true, MarkdownDescription: "Member user UUIDs."},
			"source_networks": dsschema.SetAttribute{ElementType: types.StringType, Computed: true, MarkdownDescription: "Restrict logins to these networks (CIDR)."},
		},
	}
}

func (d *groupDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *groupDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config GroupResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[groupAPIResponse](ctx, d.client, groupReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a local group", fmt.Sprintf("Could not read a local group %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
