// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package auth

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/tfconv"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// GroupResourceModel is the Terraform state model for opnsense_auth_group.
type GroupResourceModel struct {
	ID             types.String `tfsdk:"id"`
	Name           types.String `tfsdk:"name"`
	Description    types.String `tfsdk:"description"`
	Privileges     types.Set    `tfsdk:"privileges"`
	Members        types.Set    `tfsdk:"members"`
	SourceNetworks types.Set    `tfsdk:"source_networks"`
}

type groupAPIResponse struct {
	Name           string                   `json:"name"`
	Description    string                   `json:"description"`
	Privileges     opnsense.SelectedMapList `json:"priv"`
	Members        opnsense.SelectedMapList `json:"member"`
	SourceNetworks opnsense.SelectedMapList `json:"source_networks"`
}

type groupAPIRequest struct {
	Name           string `json:"name"`
	Description    string `json:"description,omitempty"`
	Privileges     string `json:"priv,omitempty"`
	Members        string `json:"member,omitempty"`
	SourceNetworks string `json:"source_networks,omitempty"`
}

func (m *GroupResourceModel) toAPI(ctx context.Context) *groupAPIRequest {
	return &groupAPIRequest{
		Name:           m.Name.ValueString(),
		Description:    m.Description.ValueString(),
		Privileges:     tfconv.SetToCSV(ctx, m.Privileges),
		Members:        tfconv.SetToCSV(ctx, m.Members),
		SourceNetworks: tfconv.SetToCSV(ctx, m.SourceNetworks),
	}
}

func (m *GroupResourceModel) fromAPI(_ context.Context, a *groupAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Name = types.StringValue(a.Name)
	m.Description = types.StringValue(a.Description)
	m.Privileges = tfconv.SliceToSet(a.Privileges)
	m.Members = tfconv.SliceToSet(a.Members)
	m.SourceNetworks = tfconv.SliceToSet(a.SourceNetworks)
}
