// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package auth_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccUser_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_auth_user", opnsense.ReqOpts{GetEndpoint: "/api/auth/user/get", Monad: "user"}),
		Steps: []resource.TestStep{
			{
				Config: testAccUserConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_auth_user.test", "id"),
			},
			{ResourceName: "opnsense_auth_user.test", ImportState: true, ImportStateVerifyIgnore: []string{"password"}, ImportStateVerify: true},
		},
	})
}

const testAccUserConfig = `
resource "opnsense_auth_user" "test" {
  name = "tfaccuser"
  password = "Tf-acc-P@ssw0rd1"
}
`
