// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package auth

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *userResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a local user on OPNsense.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource identifier.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"uid":               schema.Int64Attribute{Optional: true, Computed: true, MarkdownDescription: "Numeric user ID (auto-assigned by OPNsense).", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"name":              schema.StringAttribute{Required: true, MarkdownDescription: "Login name (unique)."},
			"password":          schema.StringAttribute{Required: true, MarkdownDescription: "User password (write-only; never read back from the API).", Sensitive: true},
			"disabled":          schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Whether this account is disabled."},
			"shell":             schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Login shell.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"full_name":         schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Full name / description.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"comment":           schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Comment.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"email":             schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Email address.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"expires":           schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Account expiry date (mm/dd/yyyy, empty = never).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"landing_page":      schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Page shown after login.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"authorized_keys":   schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Authorized SSH public keys.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"privileges":        schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, MarkdownDescription: "Assigned privilege identifiers."},
			"language":          schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Preferred GUI language.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"group_memberships": schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, MarkdownDescription: "Group UUIDs the user belongs to."},
		},
	}
}
