// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package auth

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &userDataSource{}

type userDataSource struct{ client *opnsense.Client }

func newUserDataSource() datasource.DataSource { return &userDataSource{} }

func (d *userDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_auth_user"
}

func (d *userDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Reads a local user on OPNsense by its UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID to look up.",
			},
			"uid":               dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Numeric user ID (auto-assigned by OPNsense)."},
			"name":              dsschema.StringAttribute{Computed: true, MarkdownDescription: "Login name (unique)."},
			"password":          dsschema.StringAttribute{Computed: true, MarkdownDescription: "User password (write-only; never read back from the API)."},
			"disabled":          dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether this account is disabled."},
			"shell":             dsschema.StringAttribute{Computed: true, MarkdownDescription: "Login shell."},
			"full_name":         dsschema.StringAttribute{Computed: true, MarkdownDescription: "Full name / description."},
			"comment":           dsschema.StringAttribute{Computed: true, MarkdownDescription: "Comment."},
			"email":             dsschema.StringAttribute{Computed: true, MarkdownDescription: "Email address."},
			"expires":           dsschema.StringAttribute{Computed: true, MarkdownDescription: "Account expiry date (mm/dd/yyyy, empty = never)."},
			"landing_page":      dsschema.StringAttribute{Computed: true, MarkdownDescription: "Page shown after login."},
			"authorized_keys":   dsschema.StringAttribute{Computed: true, MarkdownDescription: "Authorized SSH public keys."},
			"privileges":        dsschema.SetAttribute{ElementType: types.StringType, Computed: true, MarkdownDescription: "Assigned privilege identifiers."},
			"language":          dsschema.StringAttribute{Computed: true, MarkdownDescription: "Preferred GUI language."},
			"group_memberships": dsschema.SetAttribute{ElementType: types.StringType, Computed: true, MarkdownDescription: "Group UUIDs the user belongs to."},
		},
	}
}

func (d *userDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *userDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config UserResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[userAPIResponse](ctx, d.client, userReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a local user", fmt.Sprintf("Could not read a local user %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
