// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package firewall

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *natOneToOneResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a one-to-one (1:1) NAT rule on OPNsense.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource identifier.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"enabled":         schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(true), MarkdownDescription: "Whether this rule is enabled."},
			"log":             schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Log packets matched by this rule."},
			"sequence":        schema.Int64Attribute{Optional: true, Computed: true, MarkdownDescription: "Rule evaluation order.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"interface":       schema.StringAttribute{Required: true, MarkdownDescription: "Interface this rule applies to."},
			"type":            schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "NAT type: binat or nat (defaults to binat).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"external":        schema.StringAttribute{Required: true, MarkdownDescription: "External (public) IP address."},
			"source_net":      schema.StringAttribute{Required: true, MarkdownDescription: "Internal source network/host."},
			"source_not":      schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Invert the source match."},
			"destination_net": schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Destination network/host.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"destination_not": schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Invert the destination match."},
			"nat_reflection":  schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "NAT reflection mode (default, enable, disable).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"categories":      schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, MarkdownDescription: "Firewall category UUIDs."},
			"description":     schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Description.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}
