// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package firewall_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccNatOneToOne_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_firewall_nat_one_to_one", opnsense.ReqOpts{GetEndpoint: "/api/firewall/one_to_one/get_rule", Monad: "rule"}),
		Steps: []resource.TestStep{
			{
				Config: testAccNatOneToOneConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_firewall_nat_one_to_one.test", "id"),
			},
			{ResourceName: "opnsense_firewall_nat_one_to_one.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccNatOneToOneConfig = `

resource "opnsense_firewall_nat_one_to_one" "test" {
  interface = "wan"
  external = "192.0.2.10"
  source_net = "10.8.8.10"
  description = "tf-acc-1to1"
}
`
