// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package firewall

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &natOneToOneDataSource{}

type natOneToOneDataSource struct{ client *opnsense.Client }

func newNatOneToOneDataSource() datasource.DataSource { return &natOneToOneDataSource{} }

func (d *natOneToOneDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_firewall_nat_one_to_one"
}

func (d *natOneToOneDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Look up an existing a one-to-one (1:1) NAT rule on OPNsense by UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID of the a one-to-one (1:1) NAT rule to look up.",
			},
			"enabled":         dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether this rule is enabled."},
			"log":             dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Log packets matched by this rule."},
			"sequence":        dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Rule evaluation order."},
			"interface":       dsschema.StringAttribute{Computed: true, MarkdownDescription: "Interface this rule applies to."},
			"type":            dsschema.StringAttribute{Computed: true, MarkdownDescription: "NAT type: binat or nat (defaults to binat)."},
			"external":        dsschema.StringAttribute{Computed: true, MarkdownDescription: "External (public) IP address."},
			"source_net":      dsschema.StringAttribute{Computed: true, MarkdownDescription: "Internal source network/host."},
			"source_not":      dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Invert the source match."},
			"destination_net": dsschema.StringAttribute{Computed: true, MarkdownDescription: "Destination network/host."},
			"destination_not": dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Invert the destination match."},
			"nat_reflection":  dsschema.StringAttribute{Computed: true, MarkdownDescription: "NAT reflection mode (default, enable, disable)."},
			"categories":      dsschema.SetAttribute{ElementType: types.StringType, Computed: true, MarkdownDescription: "Firewall category UUIDs."},
			"description":     dsschema.StringAttribute{Computed: true, MarkdownDescription: "Description."},
		},
	}
}

func (d *natOneToOneDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *natOneToOneDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config NatOneToOneResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[natOneToOneAPIResponse](ctx, d.client, natOneToOneReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a one-to-one (1:1) NAT rule", fmt.Sprintf("Could not read a one-to-one (1:1) NAT rule %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
