// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package firewall

import (
	"context"
	"errors"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var (
	_ resource.Resource                = &natOneToOneResource{}
	_ resource.ResourceWithImportState = &natOneToOneResource{}
)

var natOneToOneReqOpts = opnsense.ReqOpts{
	AddEndpoint:         "/api/firewall/one_to_one/add_rule",
	GetEndpoint:         "/api/firewall/one_to_one/get_rule",
	UpdateEndpoint:      "/api/firewall/one_to_one/set_rule",
	DeleteEndpoint:      "/api/firewall/one_to_one/del_rule",
	SearchEndpoint:      "/api/firewall/one_to_one/search_rule",
	ReconfigureEndpoint: "/api/firewall/one_to_one/apply",
	Monad:               "rule",
}

type natOneToOneResource struct{ client *opnsense.Client }

func newNatOneToOneResource() resource.Resource { return &natOneToOneResource{} }

func (r *natOneToOneResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_firewall_nat_one_to_one"
}

func (r *natOneToOneResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	r.client = client
}

func (r *natOneToOneResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan NatOneToOneResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	uuid, err := opnsense.Add(ctx, r.client, natOneToOneReqOpts, plan.toAPI(ctx))
	if err != nil {
		resp.Diagnostics.AddError("Error creating a one-to-one (1:1) NAT rule", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.Get[natOneToOneAPIResponse](ctx, r.client, natOneToOneReqOpts, uuid)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a one-to-one (1:1) NAT rule after create", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, uuid)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *natOneToOneResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state NatOneToOneResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	result, err := opnsense.Get[natOneToOneAPIResponse](ctx, r.client, natOneToOneReqOpts, state.ID.ValueString())
	if err != nil {
		var nf *opnsense.NotFoundError
		if errors.As(err, &nf) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading a one-to-one (1:1) NAT rule", fmt.Sprintf("%s", err))
		return
	}
	state.fromAPI(ctx, result, state.ID.ValueString())
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *natOneToOneResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state NatOneToOneResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()
	if err := opnsense.Update(ctx, r.client, natOneToOneReqOpts, plan.toAPI(ctx), id); err != nil {
		resp.Diagnostics.AddError("Error updating a one-to-one (1:1) NAT rule", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.Get[natOneToOneAPIResponse](ctx, r.client, natOneToOneReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a one-to-one (1:1) NAT rule after update", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *natOneToOneResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state NatOneToOneResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := opnsense.Delete(ctx, r.client, natOneToOneReqOpts, state.ID.ValueString()); err != nil {
		var nf *opnsense.NotFoundError
		if errors.As(err, &nf) {
			return
		}
		resp.Diagnostics.AddError("Error deleting a one-to-one (1:1) NAT rule", fmt.Sprintf("%s", err))
	}
}

func (r *natOneToOneResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
