// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package firewall

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/tfconv"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// NatOneToOneResourceModel is the Terraform state model for opnsense_firewall_nat_one_to_one.
type NatOneToOneResourceModel struct {
	ID             types.String `tfsdk:"id"`
	Enabled        types.Bool   `tfsdk:"enabled"`
	Log            types.Bool   `tfsdk:"log"`
	Sequence       types.Int64  `tfsdk:"sequence"`
	Interface      types.String `tfsdk:"interface"`
	Type           types.String `tfsdk:"type"`
	External       types.String `tfsdk:"external"`
	SourceNet      types.String `tfsdk:"source_net"`
	SourceNot      types.Bool   `tfsdk:"source_not"`
	DestinationNet types.String `tfsdk:"destination_net"`
	DestinationNot types.Bool   `tfsdk:"destination_not"`
	NatReflection  types.String `tfsdk:"nat_reflection"`
	Categories     types.Set    `tfsdk:"categories"`
	Description    types.String `tfsdk:"description"`
}

type natOneToOneAPIResponse struct {
	Enabled        string                   `json:"enabled"`
	Log            string                   `json:"log"`
	Sequence       string                   `json:"sequence"`
	Interface      opnsense.SelectedMap     `json:"interface"`
	Type           opnsense.SelectedMap     `json:"type"`
	External       string                   `json:"external"`
	SourceNet      string                   `json:"source_net"`
	SourceNot      string                   `json:"source_not"`
	DestinationNet string                   `json:"destination_net"`
	DestinationNot string                   `json:"destination_not"`
	NatReflection  opnsense.SelectedMap     `json:"natreflection"`
	Categories     opnsense.SelectedMapList `json:"categories"`
	Description    string                   `json:"description"`
}

type natOneToOneAPIRequest struct {
	Enabled        string `json:"enabled"`
	Log            string `json:"log"`
	Sequence       string `json:"sequence,omitempty"`
	Interface      string `json:"interface"`
	Type           string `json:"type,omitempty"`
	External       string `json:"external"`
	SourceNet      string `json:"source_net"`
	SourceNot      string `json:"source_not"`
	DestinationNet string `json:"destination_net,omitempty"`
	DestinationNot string `json:"destination_not"`
	NatReflection  string `json:"natreflection,omitempty"`
	Categories     string `json:"categories,omitempty"`
	Description    string `json:"description,omitempty"`
}

func (m *NatOneToOneResourceModel) toAPI(ctx context.Context) *natOneToOneAPIRequest {
	return &natOneToOneAPIRequest{
		Enabled:        opnsense.BoolToString(m.Enabled.ValueBool()),
		Log:            opnsense.BoolToString(m.Log.ValueBool()),
		Sequence:       tfconv.IntOrEmpty(m.Sequence.ValueInt64()),
		Interface:      m.Interface.ValueString(),
		Type:           m.Type.ValueString(),
		External:       m.External.ValueString(),
		SourceNet:      m.SourceNet.ValueString(),
		SourceNot:      opnsense.BoolToString(m.SourceNot.ValueBool()),
		DestinationNet: m.DestinationNet.ValueString(),
		DestinationNot: opnsense.BoolToString(m.DestinationNot.ValueBool()),
		NatReflection:  m.NatReflection.ValueString(),
		Categories:     tfconv.SetToCSV(ctx, m.Categories),
		Description:    m.Description.ValueString(),
	}
}

func (m *NatOneToOneResourceModel) fromAPI(_ context.Context, a *natOneToOneAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Enabled = types.BoolValue(opnsense.StringToBool(a.Enabled))
	m.Log = types.BoolValue(opnsense.StringToBool(a.Log))
	m.Sequence = types.Int64Value(tfconv.IntOrZero(a.Sequence))
	m.Interface = types.StringValue(string(a.Interface))
	m.Type = types.StringValue(string(a.Type))
	m.External = types.StringValue(a.External)
	m.SourceNet = types.StringValue(a.SourceNet)
	m.SourceNot = types.BoolValue(opnsense.StringToBool(a.SourceNot))
	m.DestinationNet = types.StringValue(a.DestinationNet)
	m.DestinationNot = types.BoolValue(opnsense.StringToBool(a.DestinationNot))
	m.NatReflection = types.StringValue(string(a.NatReflection))
	m.Categories = tfconv.SliceToSet(a.Categories)
	m.Description = types.StringValue(a.Description)
}
