// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package iface

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *bridgeResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a bridge interface on OPNsense.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource identifier.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"device":      schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Assigned bridge device name (auto-assigned by OPNsense).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"members":     schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, MarkdownDescription: "Member interfaces of the bridge."},
			"protocol":    schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Spanning-tree protocol: rstp or stp.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"enable_stp":  schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Enable spanning tree on the bridge."},
			"description": schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Description.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}
