// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package iface_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccBridge_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_interface_bridge", opnsense.ReqOpts{GetEndpoint: "/api/interfaces/bridge_settings/get_item", Monad: "bridge"}),
		Steps: []resource.TestStep{
			{
				Config: testAccBridgeConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_interface_bridge.test", "id"),
			},
			{ResourceName: "opnsense_interface_bridge.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccBridgeConfig = `
resource "opnsense_interface_bridge" "test" {
  members = ["opt1"]
  description = "tf-acc-bridge"
}
`
