// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package iface

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &bridgeDataSource{}

type bridgeDataSource struct{ client *opnsense.Client }

func newBridgeDataSource() datasource.DataSource { return &bridgeDataSource{} }

func (d *bridgeDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_interface_bridge"
}

func (d *bridgeDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Reads a bridge interface on OPNsense by its UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID to look up.",
			},
			"device":      dsschema.StringAttribute{Computed: true, MarkdownDescription: "Assigned bridge device name (auto-assigned by OPNsense)."},
			"members":     dsschema.SetAttribute{ElementType: types.StringType, Computed: true, MarkdownDescription: "Member interfaces of the bridge."},
			"protocol":    dsschema.StringAttribute{Computed: true, MarkdownDescription: "Spanning-tree protocol: rstp or stp."},
			"enable_stp":  dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Enable spanning tree on the bridge."},
			"description": dsschema.StringAttribute{Computed: true, MarkdownDescription: "Description."},
		},
	}
}

func (d *bridgeDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *bridgeDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config BridgeResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[bridgeAPIResponse](ctx, d.client, bridgeReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a bridge interface", fmt.Sprintf("Could not read a bridge interface %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
