// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package iface

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/tfconv"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// BridgeResourceModel is the Terraform state model for opnsense_interface_bridge.
type BridgeResourceModel struct {
	ID          types.String `tfsdk:"id"`
	Device      types.String `tfsdk:"device"`
	Members     types.Set    `tfsdk:"members"`
	Protocol    types.String `tfsdk:"protocol"`
	EnableSTP   types.Bool   `tfsdk:"enable_stp"`
	Description types.String `tfsdk:"description"`
}

type bridgeAPIResponse struct {
	Device      string                   `json:"bridgeif"`
	Members     opnsense.SelectedMapList `json:"members"`
	Protocol    opnsense.SelectedMap     `json:"proto"`
	EnableSTP   string                   `json:"enablestp"`
	Description string                   `json:"descr"`
}

type bridgeAPIRequest struct {
	Device      string `json:"bridgeif,omitempty"`
	Members     string `json:"members,omitempty"`
	Protocol    string `json:"proto,omitempty"`
	EnableSTP   string `json:"enablestp"`
	Description string `json:"descr,omitempty"`
}

func (m *BridgeResourceModel) toAPI(ctx context.Context) *bridgeAPIRequest {
	return &bridgeAPIRequest{
		Device:      m.Device.ValueString(),
		Members:     tfconv.SetToCSV(ctx, m.Members),
		Protocol:    m.Protocol.ValueString(),
		EnableSTP:   opnsense.BoolToString(m.EnableSTP.ValueBool()),
		Description: m.Description.ValueString(),
	}
}

func (m *BridgeResourceModel) fromAPI(_ context.Context, a *bridgeAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Device = types.StringValue(a.Device)
	m.Members = tfconv.SliceToSet(a.Members)
	m.Protocol = types.StringValue(string(a.Protocol))
	m.EnableSTP = types.BoolValue(opnsense.StringToBool(a.EnableSTP))
	m.Description = types.StringValue(a.Description)
}
