// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package iface

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &gifDataSource{}

type gifDataSource struct{ client *opnsense.Client }

func newGIFDataSource() datasource.DataSource { return &gifDataSource{} }

func (d *gifDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_interface_gif"
}

func (d *gifDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Reads a GIF tunnel interface on OPNsense by its UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID to look up.",
			},
			"device":                dsschema.StringAttribute{Computed: true, MarkdownDescription: "Assigned GIF device name (auto-assigned by OPNsense)."},
			"parent_interface":      dsschema.StringAttribute{Computed: true, MarkdownDescription: "Parent interface the tunnel runs over."},
			"local_address":         dsschema.StringAttribute{Computed: true, MarkdownDescription: "Local tunnel endpoint address (must exist on the parent interface)."},
			"remote_address":        dsschema.StringAttribute{Computed: true, MarkdownDescription: "Remote tunnel endpoint address."},
			"tunnel_local_address":  dsschema.StringAttribute{Computed: true, MarkdownDescription: "Local inside (tunnel) address."},
			"tunnel_remote_address": dsschema.StringAttribute{Computed: true, MarkdownDescription: "Remote inside (tunnel) address."},
			"tunnel_remote_net":     dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Tunnel remote network prefix length."},
			"link1":                 dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Enable ECN-friendly behaviour (link1)."},
			"link2":                 dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Route the tunnel via the configured gateway (link2)."},
			"description":           dsschema.StringAttribute{Computed: true, MarkdownDescription: "Description."},
		},
	}
}

func (d *gifDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *gifDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config GIFResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[gifAPIResponse](ctx, d.client, gifReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a GIF tunnel interface", fmt.Sprintf("Could not read a GIF tunnel interface %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
