// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package iface

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/tfconv"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// GIFResourceModel is the Terraform state model for opnsense_interface_gif.
type GIFResourceModel struct {
	ID                  types.String `tfsdk:"id"`
	Device              types.String `tfsdk:"device"`
	ParentInterface     types.String `tfsdk:"parent_interface"`
	LocalAddress        types.String `tfsdk:"local_address"`
	RemoteAddress       types.String `tfsdk:"remote_address"`
	TunnelLocalAddress  types.String `tfsdk:"tunnel_local_address"`
	TunnelRemoteAddress types.String `tfsdk:"tunnel_remote_address"`
	TunnelRemoteNet     types.Int64  `tfsdk:"tunnel_remote_net"`
	Link1               types.Bool   `tfsdk:"link1"`
	Link2               types.Bool   `tfsdk:"link2"`
	Description         types.String `tfsdk:"description"`
}

type gifAPIResponse struct {
	Device              string `json:"gifif"`
	ParentInterface     string `json:"if"`
	LocalAddress        string `json:"local-addr"`
	RemoteAddress       string `json:"remote-addr"`
	TunnelLocalAddress  string `json:"tunnel-local-addr"`
	TunnelRemoteAddress string `json:"tunnel-remote-addr"`
	TunnelRemoteNet     string `json:"tunnel-remote-net"`
	Link1               string `json:"link1"`
	Link2               string `json:"link2"`
	Description         string `json:"descr"`
}

type gifAPIRequest struct {
	Device              string `json:"gifif,omitempty"`
	ParentInterface     string `json:"if"`
	LocalAddress        string `json:"local-addr"`
	RemoteAddress       string `json:"remote-addr"`
	TunnelLocalAddress  string `json:"tunnel-local-addr"`
	TunnelRemoteAddress string `json:"tunnel-remote-addr"`
	TunnelRemoteNet     string `json:"tunnel-remote-net,omitempty"`
	Link1               string `json:"link1"`
	Link2               string `json:"link2"`
	Description         string `json:"descr,omitempty"`
}

func (m *GIFResourceModel) toAPI(_ context.Context) *gifAPIRequest {
	return &gifAPIRequest{
		Device:              m.Device.ValueString(),
		ParentInterface:     m.ParentInterface.ValueString(),
		LocalAddress:        m.LocalAddress.ValueString(),
		RemoteAddress:       m.RemoteAddress.ValueString(),
		TunnelLocalAddress:  m.TunnelLocalAddress.ValueString(),
		TunnelRemoteAddress: m.TunnelRemoteAddress.ValueString(),
		TunnelRemoteNet:     tfconv.IntOrEmpty(m.TunnelRemoteNet.ValueInt64()),
		Link1:               opnsense.BoolToString(m.Link1.ValueBool()),
		Link2:               opnsense.BoolToString(m.Link2.ValueBool()),
		Description:         m.Description.ValueString(),
	}
}

func (m *GIFResourceModel) fromAPI(_ context.Context, a *gifAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Device = types.StringValue(a.Device)
	m.ParentInterface = types.StringValue(a.ParentInterface)
	m.LocalAddress = types.StringValue(a.LocalAddress)
	m.RemoteAddress = types.StringValue(a.RemoteAddress)
	m.TunnelLocalAddress = types.StringValue(a.TunnelLocalAddress)
	m.TunnelRemoteAddress = types.StringValue(a.TunnelRemoteAddress)
	m.TunnelRemoteNet = types.Int64Value(tfconv.IntOrZero(a.TunnelRemoteNet))
	m.Link1 = types.BoolValue(opnsense.StringToBool(a.Link1))
	m.Link2 = types.BoolValue(opnsense.StringToBool(a.Link2))
	m.Description = types.StringValue(a.Description)
}
