// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package iface_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccGIF_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_interface_gif", opnsense.ReqOpts{GetEndpoint: "/api/interfaces/gif_settings/get_item", Monad: "gif"}),
		Steps: []resource.TestStep{
			{
				Config: testAccGIFConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_interface_gif.test", "id"),
			},
			{ResourceName: "opnsense_interface_gif.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccGIFConfig = `
resource "opnsense_interface_gif" "test" {
  parent_interface = "lan"
  local_address = "192.168.56.10"
  remote_address = "192.0.2.98"
  tunnel_local_address = "10.6.6.1"
  tunnel_remote_address = "10.6.6.2"
  description = "tf-acc-gif"
}
`
