// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package iface

import (
	"context"
	"errors"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var (
	_ resource.Resource                = &gifResource{}
	_ resource.ResourceWithImportState = &gifResource{}
)

var gifReqOpts = opnsense.ReqOpts{
	AddEndpoint:         "/api/interfaces/gif_settings/add_item",
	GetEndpoint:         "/api/interfaces/gif_settings/get_item",
	UpdateEndpoint:      "/api/interfaces/gif_settings/set_item",
	DeleteEndpoint:      "/api/interfaces/gif_settings/del_item",
	SearchEndpoint:      "/api/interfaces/gif_settings/search_item",
	ReconfigureEndpoint: "/api/interfaces/gif_settings/reconfigure",
	Monad:               "gif",
}

type gifResource struct{ client *opnsense.Client }

func newGIFResource() resource.Resource { return &gifResource{} }

func (r *gifResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_interface_gif"
}

func (r *gifResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	r.client = client
}

func (r *gifResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan GIFResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	uuid, err := opnsense.Add(ctx, r.client, gifReqOpts, plan.toAPI(ctx))
	if err != nil {
		resp.Diagnostics.AddError("Error creating a GIF tunnel interface", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.Get[gifAPIResponse](ctx, r.client, gifReqOpts, uuid)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a GIF tunnel interface after create", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, uuid)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *gifResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state GIFResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	result, err := opnsense.Get[gifAPIResponse](ctx, r.client, gifReqOpts, state.ID.ValueString())
	if err != nil {
		var nf *opnsense.NotFoundError
		if errors.As(err, &nf) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading a GIF tunnel interface", fmt.Sprintf("%s", err))
		return
	}
	state.fromAPI(ctx, result, state.ID.ValueString())
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *gifResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state GIFResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()
	if err := opnsense.Update(ctx, r.client, gifReqOpts, plan.toAPI(ctx), id); err != nil {
		resp.Diagnostics.AddError("Error updating a GIF tunnel interface", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.Get[gifAPIResponse](ctx, r.client, gifReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a GIF tunnel interface after update", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *gifResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state GIFResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := opnsense.Delete(ctx, r.client, gifReqOpts, state.ID.ValueString()); err != nil {
		var nf *opnsense.NotFoundError
		if errors.As(err, &nf) {
			return
		}
		resp.Diagnostics.AddError("Error deleting a GIF tunnel interface", fmt.Sprintf("%s", err))
	}
}

func (r *gifResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
