// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package iface

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/tfconv"
)

// GREResourceModel is the Terraform state model for opnsense_interface_gre.
type GREResourceModel struct {
	ID                  types.String `tfsdk:"id"`
	Device              types.String `tfsdk:"device"`
	ParentInterface     types.String `tfsdk:"parent_interface"`
	LocalAddress        types.String `tfsdk:"local_address"`
	RemoteAddress       types.String `tfsdk:"remote_address"`
	TunnelLocalAddress  types.String `tfsdk:"tunnel_local_address"`
	TunnelRemoteAddress types.String `tfsdk:"tunnel_remote_address"`
	TunnelRemoteNet     types.Int64  `tfsdk:"tunnel_remote_net"`
	Description         types.String `tfsdk:"description"`
}

type greAPIResponse struct {
	Device              string `json:"greif"`
	ParentInterface     string `json:"if"`
	LocalAddress        string `json:"local-addr"`
	RemoteAddress       string `json:"remote-addr"`
	TunnelLocalAddress  string `json:"tunnel-local-addr"`
	TunnelRemoteAddress string `json:"tunnel-remote-addr"`
	TunnelRemoteNet     string `json:"tunnel-remote-net"`
	Description         string `json:"descr"`
}

type greAPIRequest struct {
	Device              string `json:"greif,omitempty"`
	ParentInterface     string `json:"if"`
	LocalAddress        string `json:"local-addr"`
	RemoteAddress       string `json:"remote-addr"`
	TunnelLocalAddress  string `json:"tunnel-local-addr"`
	TunnelRemoteAddress string `json:"tunnel-remote-addr"`
	TunnelRemoteNet     string `json:"tunnel-remote-net,omitempty"`
	Description         string `json:"descr,omitempty"`
}

func (m *GREResourceModel) toAPI(_ context.Context) *greAPIRequest {
	return &greAPIRequest{
		Device:              m.Device.ValueString(),
		ParentInterface:     m.ParentInterface.ValueString(),
		LocalAddress:        m.LocalAddress.ValueString(),
		RemoteAddress:       m.RemoteAddress.ValueString(),
		TunnelLocalAddress:  m.TunnelLocalAddress.ValueString(),
		TunnelRemoteAddress: m.TunnelRemoteAddress.ValueString(),
		TunnelRemoteNet:     tfconv.IntOrEmpty(m.TunnelRemoteNet.ValueInt64()),
		Description:         m.Description.ValueString(),
	}
}

func (m *GREResourceModel) fromAPI(_ context.Context, a *greAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Device = types.StringValue(a.Device)
	m.ParentInterface = types.StringValue(a.ParentInterface)
	m.LocalAddress = types.StringValue(a.LocalAddress)
	m.RemoteAddress = types.StringValue(a.RemoteAddress)
	m.TunnelLocalAddress = types.StringValue(a.TunnelLocalAddress)
	m.TunnelRemoteAddress = types.StringValue(a.TunnelRemoteAddress)
	m.TunnelRemoteNet = types.Int64Value(tfconv.IntOrZero(a.TunnelRemoteNet))
	m.Description = types.StringValue(a.Description)
}
