// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package iface

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

func (r *greResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a GRE tunnel interface on OPNsense.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource identifier.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"device":                schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Assigned GRE device name (auto-assigned by OPNsense).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"parent_interface":      schema.StringAttribute{Required: true, MarkdownDescription: "Parent interface the tunnel runs over."},
			"local_address":         schema.StringAttribute{Required: true, MarkdownDescription: "Local tunnel endpoint address (must exist on the parent interface)."},
			"remote_address":        schema.StringAttribute{Required: true, MarkdownDescription: "Remote tunnel endpoint address."},
			"tunnel_local_address":  schema.StringAttribute{Required: true, MarkdownDescription: "Local inside (tunnel) address."},
			"tunnel_remote_address": schema.StringAttribute{Required: true, MarkdownDescription: "Remote inside (tunnel) address."},
			"tunnel_remote_net":     schema.Int64Attribute{Optional: true, Computed: true, MarkdownDescription: "Tunnel remote network prefix length.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"description":           schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Description.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}
