// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package iface

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/setvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *laggResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a LAGG interface on OPNsense.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource identifier.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"device":            schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Assigned LAGG device name (auto-assigned by OPNsense).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"members":           schema.SetAttribute{ElementType: types.StringType, Required: true, MarkdownDescription: "Member interfaces in the LAGG. Use free, non-management physical interfaces from the test appliance."},
			"primary_member":    schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Primary member interface; must be one of the member interfaces when set.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"protocol":          schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "LAGG protocol: none, lacp, failover, fec, loadbalance, or roundrobin.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}, Validators: []validator.String{stringvalidator.OneOf("none", "lacp", "failover", "fec", "loadbalance", "roundrobin")}},
			"lacp_fast_timeout": schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Use LACP fast timeout."},
			"use_flowid":        schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Use flow ID: empty for default, 1 for yes, 0 for no.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}, Validators: []validator.String{stringvalidator.OneOf("", "1", "0")}},
			"lagg_hash":         schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, MarkdownDescription: "Hash layers for protocols that support hash selection: l2, l3, and/or l4.", Validators: []validator.Set{setvalidator.ValueStringsAre(stringvalidator.OneOf("l2", "l3", "l4"))}},
			"lacp_strict":       schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "LACP strict mode: empty for default, 1 for yes, 0 for no.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}, Validators: []validator.String{stringvalidator.OneOf("", "1", "0")}},
			"mtu":               schema.Int64Attribute{Optional: true, Computed: true, MarkdownDescription: "MTU for the LAGG interface (576-65535).", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}, Validators: []validator.Int64{int64validator.Between(576, 65535)}},
			"description":       schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Description.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}
