// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package iface

import (
	"context"
	"errors"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var (
	_ resource.Resource                = &laggResource{}
	_ resource.ResourceWithImportState = &laggResource{}
)

var laggReqOpts = opnsense.ReqOpts{
	AddEndpoint:         "/api/interfaces/lagg_settings/add_item",
	GetEndpoint:         "/api/interfaces/lagg_settings/get_item",
	UpdateEndpoint:      "/api/interfaces/lagg_settings/set_item",
	DeleteEndpoint:      "/api/interfaces/lagg_settings/del_item",
	SearchEndpoint:      "/api/interfaces/lagg_settings/search_item",
	ReconfigureEndpoint: "/api/interfaces/lagg_settings/reconfigure",
	Monad:               "lagg",
}

type laggResource struct{ client *opnsense.Client }

func newLaggResource() resource.Resource { return &laggResource{} }

func (r *laggResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_interface_lagg"
}

func (r *laggResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	r.client = client
}

func (r *laggResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan LaggResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	uuid, err := opnsense.Add(ctx, r.client, laggReqOpts, plan.toAPI(ctx))
	if err != nil {
		resp.Diagnostics.AddError("Error creating a LAGG interface", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.Get[laggAPIResponse](ctx, r.client, laggReqOpts, uuid)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a LAGG interface after create", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, uuid)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *laggResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state LaggResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	result, err := opnsense.Get[laggAPIResponse](ctx, r.client, laggReqOpts, state.ID.ValueString())
	if err != nil {
		var nf *opnsense.NotFoundError
		if errors.As(err, &nf) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading a LAGG interface", fmt.Sprintf("%s", err))
		return
	}
	state.fromAPI(ctx, result, state.ID.ValueString())
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *laggResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state LaggResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()
	if err := opnsense.Update(ctx, r.client, laggReqOpts, plan.toAPI(ctx), id); err != nil {
		resp.Diagnostics.AddError("Error updating a LAGG interface", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.Get[laggAPIResponse](ctx, r.client, laggReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a LAGG interface after update", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *laggResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state LaggResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := opnsense.Delete(ctx, r.client, laggReqOpts, state.ID.ValueString()); err != nil {
		var nf *opnsense.NotFoundError
		if errors.As(err, &nf) {
			return
		}
		resp.Diagnostics.AddError("Error deleting a LAGG interface", fmt.Sprintf("%s", err))
	}
}

func (r *laggResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
