// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package iface_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccLagg_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_interface_lagg", opnsense.ReqOpts{GetEndpoint: "/api/interfaces/lagg_settings/get_item", Monad: "lagg"}),
		Steps: []resource.TestStep{
			{
				Config: testAccLaggConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_interface_lagg.test", "id"),
			},
			{
				Config: testAccLaggUpdatedConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_interface_lagg.test", "id"),
			},
			{ResourceName: "opnsense_interface_lagg.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccLaggConfig = `

resource "opnsense_interface_lagg" "test" {
  members = ["em4", "em5"]
  protocol = "failover"
  description = "tf-acc-lagg"
}
`

const testAccLaggUpdatedConfig = `

resource "opnsense_interface_lagg" "test" {
  members = ["em4", "em5"]
  protocol = "failover"
  description = "tf-acc-lagg-updated"
}
`
