// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package iface

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/tfconv"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// LaggResourceModel is the Terraform state model for opnsense_interface_lagg.
type LaggResourceModel struct {
	ID              types.String `tfsdk:"id"`
	Device          types.String `tfsdk:"device"`
	Members         types.Set    `tfsdk:"members"`
	PrimaryMember   types.String `tfsdk:"primary_member"`
	Protocol        types.String `tfsdk:"protocol"`
	LACPFastTimeout types.Bool   `tfsdk:"lacp_fast_timeout"`
	UseFlowID       types.String `tfsdk:"use_flowid"`
	LaggHash        types.Set    `tfsdk:"lagg_hash"`
	LACPStrict      types.String `tfsdk:"lacp_strict"`
	MTU             types.Int64  `tfsdk:"mtu"`
	Description     types.String `tfsdk:"description"`
}

type laggAPIResponse struct {
	Device          string                   `json:"laggif"`
	Members         opnsense.SelectedMapList `json:"members"`
	PrimaryMember   opnsense.SelectedMap     `json:"primary_member"`
	Protocol        opnsense.SelectedMap     `json:"proto"`
	LACPFastTimeout string                   `json:"lacp_fast_timeout"`
	UseFlowID       opnsense.SelectedMap     `json:"use_flowid"`
	LaggHash        opnsense.SelectedMapList `json:"lagghash"`
	LACPStrict      opnsense.SelectedMap     `json:"lacp_strict"`
	MTU             string                   `json:"mtu"`
	Description     string                   `json:"descr"`
}

type laggAPIRequest struct {
	Device          string `json:"laggif,omitempty"`
	Members         string `json:"members"`
	PrimaryMember   string `json:"primary_member,omitempty"`
	Protocol        string `json:"proto,omitempty"`
	LACPFastTimeout string `json:"lacp_fast_timeout"`
	UseFlowID       string `json:"use_flowid,omitempty"`
	LaggHash        string `json:"lagghash,omitempty"`
	LACPStrict      string `json:"lacp_strict,omitempty"`
	MTU             string `json:"mtu,omitempty"`
	Description     string `json:"descr,omitempty"`
}

func (m *LaggResourceModel) toAPI(ctx context.Context) *laggAPIRequest {
	return &laggAPIRequest{
		Device:          m.Device.ValueString(),
		Members:         tfconv.SetToCSV(ctx, m.Members),
		PrimaryMember:   m.PrimaryMember.ValueString(),
		Protocol:        m.Protocol.ValueString(),
		LACPFastTimeout: opnsense.BoolToString(m.LACPFastTimeout.ValueBool()),
		UseFlowID:       m.UseFlowID.ValueString(),
		LaggHash:        tfconv.SetToCSV(ctx, m.LaggHash),
		LACPStrict:      m.LACPStrict.ValueString(),
		MTU:             tfconv.IntOrEmpty(m.MTU.ValueInt64()),
		Description:     m.Description.ValueString(),
	}
}

func (m *LaggResourceModel) fromAPI(_ context.Context, a *laggAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Device = types.StringValue(a.Device)
	m.Members = tfconv.SliceToSet(a.Members)
	m.PrimaryMember = types.StringValue(string(a.PrimaryMember))
	m.Protocol = types.StringValue(string(a.Protocol))
	m.LACPFastTimeout = types.BoolValue(opnsense.StringToBool(a.LACPFastTimeout))
	m.UseFlowID = types.StringValue(string(a.UseFlowID))
	m.LaggHash = tfconv.SliceToSet(a.LaggHash)
	m.LACPStrict = types.StringValue(string(a.LACPStrict))
	m.MTU = types.Int64Value(tfconv.IntOrZero(a.MTU))
	m.Description = types.StringValue(a.Description)
}
