// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package iface

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &laggDataSource{}

type laggDataSource struct{ client *opnsense.Client }

func newLaggDataSource() datasource.DataSource { return &laggDataSource{} }

func (d *laggDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_interface_lagg"
}

func (d *laggDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Reads a LAGG interface on OPNsense by its UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID to look up.",
			},
			"device":            dsschema.StringAttribute{Computed: true, MarkdownDescription: "Assigned LAGG device name (auto-assigned by OPNsense)."},
			"members":           dsschema.SetAttribute{ElementType: types.StringType, Computed: true, MarkdownDescription: "Member interfaces in the LAGG. Use free, non-management physical interfaces from the test appliance."},
			"primary_member":    dsschema.StringAttribute{Computed: true, MarkdownDescription: "Primary member interface; must be one of the member interfaces when set."},
			"protocol":          dsschema.StringAttribute{Computed: true, MarkdownDescription: "LAGG protocol: none, lacp, failover, fec, loadbalance, or roundrobin."},
			"lacp_fast_timeout": dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Use LACP fast timeout."},
			"use_flowid":        dsschema.StringAttribute{Computed: true, MarkdownDescription: "Use flow ID: empty for default, 1 for yes, 0 for no."},
			"lagg_hash":         dsschema.SetAttribute{ElementType: types.StringType, Computed: true, MarkdownDescription: "Hash layers for protocols that support hash selection: l2, l3, and/or l4."},
			"lacp_strict":       dsschema.StringAttribute{Computed: true, MarkdownDescription: "LACP strict mode: empty for default, 1 for yes, 0 for no."},
			"mtu":               dsschema.Int64Attribute{Computed: true, MarkdownDescription: "MTU for the LAGG interface (576-65535)."},
			"description":       dsschema.StringAttribute{Computed: true, MarkdownDescription: "Description."},
		},
	}
}

func (d *laggDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *laggDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config LaggResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[laggAPIResponse](ctx, d.client, laggReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a LAGG interface", fmt.Sprintf("Could not read a LAGG interface %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
