// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package iface

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/tfconv"
)

// LoopbackResourceModel is the Terraform state model for opnsense_interface_loopback.
type LoopbackResourceModel struct {
	ID          types.String `tfsdk:"id"`
	DeviceID    types.Int64  `tfsdk:"device_id"`
	Description types.String `tfsdk:"description"`
}

type loopbackAPIResponse struct {
	DeviceID    string `json:"deviceId"`
	Description string `json:"description"`
}

type loopbackAPIRequest struct {
	DeviceID    string `json:"deviceId,omitempty"`
	Description string `json:"description"`
}

func (m *LoopbackResourceModel) toAPI(_ context.Context) *loopbackAPIRequest {
	return &loopbackAPIRequest{
		DeviceID:    tfconv.IntOrEmpty(m.DeviceID.ValueInt64()),
		Description: m.Description.ValueString(),
	}
}

func (m *LoopbackResourceModel) fromAPI(_ context.Context, a *loopbackAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.DeviceID = types.Int64Value(tfconv.IntOrZero(a.DeviceID))
	m.Description = types.StringValue(a.Description)
}
