// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package iface_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccLoopback_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_interface_loopback", opnsense.ReqOpts{GetEndpoint: "/api/interfaces/loopback_settings/get_item", Monad: "loopback"}),
		Steps: []resource.TestStep{
			{
				Config: testAccLoopbackConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_interface_loopback.test", "id"),
			},
			{ResourceName: "opnsense_interface_loopback.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccLoopbackConfig = `

resource "opnsense_interface_loopback" "test" {
  description = "tf-acc-loopback"
}
`
