// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package iface

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &neighborDataSource{}

type neighborDataSource struct{ client *opnsense.Client }

func newNeighborDataSource() datasource.DataSource { return &neighborDataSource{} }

func (d *neighborDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_interface_neighbor"
}

func (d *neighborDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Look up an existing a static ARP/NDP neighbor on OPNsense by UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID of the a static ARP/NDP neighbor to look up.",
			},
			"mac":         dsschema.StringAttribute{Computed: true, MarkdownDescription: "MAC (ethernet) address."},
			"ip_address":  dsschema.StringAttribute{Computed: true, MarkdownDescription: "IP address for the static entry."},
			"description": dsschema.StringAttribute{Computed: true, MarkdownDescription: "Description."},
		},
	}
}

func (d *neighborDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *neighborDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config NeighborResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[neighborAPIResponse](ctx, d.client, neighborReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a static ARP/NDP neighbor", fmt.Sprintf("Could not read a static ARP/NDP neighbor %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
