// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package iface_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccNeighbor_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_interface_neighbor", opnsense.ReqOpts{GetEndpoint: "/api/interfaces/neighbor_settings/get_item", Monad: "neighbor"}),
		Steps: []resource.TestStep{
			{
				Config: testAccNeighborConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_interface_neighbor.test", "id"),
			},
			{ResourceName: "opnsense_interface_neighbor.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccNeighborConfig = `
resource "opnsense_interface_neighbor" "test" {
  mac = "00:11:22:33:44:55"
  ip_address = "192.0.2.5"
}
`
