// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package iface_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccVxlan_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_interface_vxlan", opnsense.ReqOpts{GetEndpoint: "/api/interfaces/vxlan_settings/get_item", Monad: "vxlan"}),
		Steps: []resource.TestStep{
			{
				Config: testAccVxlanConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_interface_vxlan.test", "id"),
			},
			{ResourceName: "opnsense_interface_vxlan.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccVxlanConfig = `
resource "opnsense_interface_vxlan" "test" {
  vni = 100
  local = "192.168.56.10"
  remote = "192.0.2.50"
}
`
