// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package iface

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

func (r *vxlanResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a VXLAN interface on OPNsense.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource identifier.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"device_id": schema.Int64Attribute{Optional: true, Computed: true, MarkdownDescription: "VXLAN device number (auto-assigned by OPNsense).", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"vni":       schema.Int64Attribute{Required: true, MarkdownDescription: "VXLAN network identifier (0-16777215)."},
			"local":     schema.StringAttribute{Required: true, MarkdownDescription: "Local source IP address."},
			"remote":    schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Remote peer IP (unicast mode).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"group":     schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Multicast group IP (multicast mode).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"device":    schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Underlying interface.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}
