// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package iface

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &vxlanDataSource{}

type vxlanDataSource struct{ client *opnsense.Client }

func newVxlanDataSource() datasource.DataSource { return &vxlanDataSource{} }

func (d *vxlanDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_interface_vxlan"
}

func (d *vxlanDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Look up an existing a VXLAN interface on OPNsense by UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID of the a VXLAN interface to look up.",
			},
			"device_id": dsschema.Int64Attribute{Computed: true, MarkdownDescription: "VXLAN device number (auto-assigned by OPNsense)."},
			"vni":       dsschema.Int64Attribute{Computed: true, MarkdownDescription: "VXLAN network identifier (0-16777215)."},
			"local":     dsschema.StringAttribute{Computed: true, MarkdownDescription: "Local source IP address."},
			"remote":    dsschema.StringAttribute{Computed: true, MarkdownDescription: "Remote peer IP (unicast mode)."},
			"group":     dsschema.StringAttribute{Computed: true, MarkdownDescription: "Multicast group IP (multicast mode)."},
			"device":    dsschema.StringAttribute{Computed: true, MarkdownDescription: "Underlying interface."},
		},
	}
}

func (d *vxlanDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *vxlanDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config VxlanResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[vxlanAPIResponse](ctx, d.client, vxlanReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a VXLAN interface", fmt.Sprintf("Could not read a VXLAN interface %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
