// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package iface

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/tfconv"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// VxlanResourceModel is the Terraform state model for opnsense_interface_vxlan.
type VxlanResourceModel struct {
	ID       types.String `tfsdk:"id"`
	DeviceID types.Int64  `tfsdk:"device_id"`
	VNI      types.Int64  `tfsdk:"vni"`
	Local    types.String `tfsdk:"local"`
	Remote   types.String `tfsdk:"remote"`
	Group    types.String `tfsdk:"group"`
	Device   types.String `tfsdk:"device"`
}

type vxlanAPIResponse struct {
	DeviceID string               `json:"deviceId"`
	VNI      string               `json:"vxlanid"`
	Local    string               `json:"vxlanlocal"`
	Remote   string               `json:"vxlanremote"`
	Group    string               `json:"vxlangroup"`
	Device   opnsense.SelectedMap `json:"vxlandev"`
}

type vxlanAPIRequest struct {
	DeviceID string `json:"deviceId,omitempty"`
	VNI      string `json:"vxlanid"`
	Local    string `json:"vxlanlocal"`
	Remote   string `json:"vxlanremote,omitempty"`
	Group    string `json:"vxlangroup,omitempty"`
	Device   string `json:"vxlandev,omitempty"`
}

func (m *VxlanResourceModel) toAPI(_ context.Context) *vxlanAPIRequest {
	return &vxlanAPIRequest{
		DeviceID: tfconv.IntOrEmpty(m.DeviceID.ValueInt64()),
		VNI:      opnsense.Int64ToString(m.VNI.ValueInt64()),
		Local:    m.Local.ValueString(),
		Remote:   m.Remote.ValueString(),
		Group:    m.Group.ValueString(),
		Device:   m.Device.ValueString(),
	}
}

func (m *VxlanResourceModel) fromAPI(_ context.Context, a *vxlanAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.DeviceID = types.Int64Value(tfconv.IntOrZero(a.DeviceID))
	m.VNI = types.Int64Value(tfconv.IntOrZero(a.VNI))
	m.Local = types.StringValue(a.Local)
	m.Remote = types.StringValue(a.Remote)
	m.Group = types.StringValue(a.Group)
	m.Device = types.StringValue(string(a.Device))
}
