// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package monit

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &alertDataSource{}

type alertDataSource struct{ client *opnsense.Client }

func newAlertDataSource() datasource.DataSource { return &alertDataSource{} }

func (d *alertDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_monit_alert"
}

func (d *alertDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Reads a monit alert on OPNsense by its UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID to look up.",
			},
			"enabled":     dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether this alert is enabled."},
			"recipient":   dsschema.StringAttribute{Computed: true, MarkdownDescription: "Email recipient."},
			"not_on":      dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Invert the event filter (alert on all except selected)."},
			"events":      dsschema.SetAttribute{ElementType: types.StringType, Computed: true, MarkdownDescription: "Events to alert on (empty = all)."},
			"format":      dsschema.StringAttribute{Computed: true, MarkdownDescription: "Custom alert message format."},
			"reminder":    dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Reminder interval in cycles (0 = unset)."},
			"description": dsschema.StringAttribute{Computed: true, MarkdownDescription: "Description."},
		},
	}
}

func (d *alertDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *alertDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config AlertResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[alertAPIResponse](ctx, d.client, alertReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a monit alert", fmt.Sprintf("Could not read a monit alert %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
