// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package monit_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccAlert_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_monit_alert", opnsense.ReqOpts{GetEndpoint: "/api/monit/settings/get_alert", Monad: "alert"}),
		Steps: []resource.TestStep{
			{
				Config: testAccAlertConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_monit_alert.test", "id"),
			},
			{ResourceName: "opnsense_monit_alert.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccAlertConfig = `
resource "opnsense_monit_alert" "test" {
  recipient = "test@example.com"
}
`
