// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package monit

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &serviceDataSource{}

type serviceDataSource struct{ client *opnsense.Client }

func newServiceDataSource() datasource.DataSource { return &serviceDataSource{} }

func (d *serviceDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_monit_service"
}

func (d *serviceDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Look up an existing a monit service on OPNsense by UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID of the a monit service to look up.",
			},
			"enabled":       dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether this service check is enabled."},
			"name":          dsschema.StringAttribute{Computed: true, MarkdownDescription: "Service name."},
			"description":   dsschema.StringAttribute{Computed: true, MarkdownDescription: "Description."},
			"type":          dsschema.StringAttribute{Computed: true, MarkdownDescription: "Service type (process, file, host, system, network, ...)."},
			"pidfile":       dsschema.StringAttribute{Computed: true, MarkdownDescription: "PID file path (process type)."},
			"match":         dsschema.StringAttribute{Computed: true, MarkdownDescription: "Process match string."},
			"path":          dsschema.StringAttribute{Computed: true, MarkdownDescription: "Path (file/filesystem types)."},
			"timeout":       dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Restart timeout in seconds."},
			"start_timeout": dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Start timeout in seconds."},
			"address":       dsschema.StringAttribute{Computed: true, MarkdownDescription: "Address (host/network types)."},
			"interface":     dsschema.StringAttribute{Computed: true, MarkdownDescription: "Interface (network type)."},
			"start":         dsschema.StringAttribute{Computed: true, MarkdownDescription: "Start program command."},
			"stop":          dsschema.StringAttribute{Computed: true, MarkdownDescription: "Stop program command."},
			"tests":         dsschema.SetAttribute{ElementType: types.StringType, Computed: true, MarkdownDescription: "UUIDs of monit tests applied to this service."},
		},
	}
}

func (d *serviceDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *serviceDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config ServiceResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[serviceAPIResponse](ctx, d.client, serviceReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a monit service", fmt.Sprintf("Could not read a monit service %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
