// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package monit

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/tfconv"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// ServiceResourceModel is the Terraform state model for opnsense_monit_service.
type ServiceResourceModel struct {
	ID           types.String `tfsdk:"id"`
	Enabled      types.Bool   `tfsdk:"enabled"`
	Name         types.String `tfsdk:"name"`
	Description  types.String `tfsdk:"description"`
	Type         types.String `tfsdk:"type"`
	PIDFile      types.String `tfsdk:"pidfile"`
	Match        types.String `tfsdk:"match"`
	Path         types.String `tfsdk:"path"`
	Timeout      types.Int64  `tfsdk:"timeout"`
	StartTimeout types.Int64  `tfsdk:"start_timeout"`
	Address      types.String `tfsdk:"address"`
	Interface    types.String `tfsdk:"interface"`
	Start        types.String `tfsdk:"start"`
	Stop         types.String `tfsdk:"stop"`
	Tests        types.Set    `tfsdk:"tests"`
}

type serviceAPIResponse struct {
	Enabled      string                   `json:"enabled"`
	Name         string                   `json:"name"`
	Description  string                   `json:"description"`
	Type         opnsense.SelectedMap     `json:"type"`
	PIDFile      string                   `json:"pidfile"`
	Match        string                   `json:"match"`
	Path         string                   `json:"path"`
	Timeout      string                   `json:"timeout"`
	StartTimeout string                   `json:"starttimeout"`
	Address      string                   `json:"address"`
	Interface    opnsense.SelectedMap     `json:"interface"`
	Start        string                   `json:"start"`
	Stop         string                   `json:"stop"`
	Tests        opnsense.SelectedMapList `json:"tests"`
}

type serviceAPIRequest struct {
	Enabled      string `json:"enabled"`
	Name         string `json:"name"`
	Description  string `json:"description"`
	Type         string `json:"type"`
	PIDFile      string `json:"pidfile"`
	Match        string `json:"match"`
	Path         string `json:"path"`
	Timeout      string `json:"timeout"`
	StartTimeout string `json:"starttimeout"`
	Address      string `json:"address"`
	Interface    string `json:"interface"`
	Start        string `json:"start"`
	Stop         string `json:"stop"`
	Tests        string `json:"tests"`
}

func (m *ServiceResourceModel) toAPI(ctx context.Context) *serviceAPIRequest {
	return &serviceAPIRequest{
		Enabled:      opnsense.BoolToString(m.Enabled.ValueBool()),
		Name:         m.Name.ValueString(),
		Description:  m.Description.ValueString(),
		Type:         m.Type.ValueString(),
		PIDFile:      m.PIDFile.ValueString(),
		Match:        m.Match.ValueString(),
		Path:         m.Path.ValueString(),
		Timeout:      tfconv.IntOrEmpty(m.Timeout.ValueInt64()),
		StartTimeout: tfconv.IntOrEmpty(m.StartTimeout.ValueInt64()),
		Address:      m.Address.ValueString(),
		Interface:    m.Interface.ValueString(),
		Start:        m.Start.ValueString(),
		Stop:         m.Stop.ValueString(),
		Tests:        tfconv.SetToCSV(ctx, m.Tests),
	}
}

func (m *ServiceResourceModel) fromAPI(_ context.Context, a *serviceAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Enabled = types.BoolValue(opnsense.StringToBool(a.Enabled))
	m.Name = types.StringValue(a.Name)
	m.Description = types.StringValue(a.Description)
	m.Type = types.StringValue(string(a.Type))
	m.PIDFile = types.StringValue(a.PIDFile)
	m.Match = types.StringValue(a.Match)
	m.Path = types.StringValue(a.Path)
	m.Timeout = types.Int64Value(tfconv.IntOrZero(a.Timeout))
	m.StartTimeout = types.Int64Value(tfconv.IntOrZero(a.StartTimeout))
	m.Address = types.StringValue(a.Address)
	m.Interface = types.StringValue(string(a.Interface))
	m.Start = types.StringValue(a.Start)
	m.Stop = types.StringValue(a.Stop)
	m.Tests = tfconv.SliceToSet(a.Tests)
}
