// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package monit

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &testDataSource{}

type testDataSource struct{ client *opnsense.Client }

func newTestDataSource() datasource.DataSource { return &testDataSource{} }

func (d *testDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_monit_test"
}

func (d *testDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Reads a monit test on OPNsense by its UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID to look up.",
			},
			"name":      dsschema.StringAttribute{Computed: true, MarkdownDescription: "Test name."},
			"type":      dsschema.StringAttribute{Computed: true, MarkdownDescription: "Test type (e.g. SystemResource, ProcessMemory)."},
			"condition": dsschema.StringAttribute{Computed: true, MarkdownDescription: "Monit condition expression."},
			"action":    dsschema.StringAttribute{Computed: true, MarkdownDescription: "Action on match (alert, restart, stop, exec, ...)."},
			"path":      dsschema.StringAttribute{Computed: true, MarkdownDescription: "Path/program for exec action."},
		},
	}
}

func (d *testDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *testDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config TestResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[testAPIResponse](ctx, d.client, testReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a monit test", fmt.Sprintf("Could not read a monit test %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
