// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package monit

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

func (r *testResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a monit test on OPNsense.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource identifier.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"name":      schema.StringAttribute{Required: true, MarkdownDescription: "Test name."},
			"type":      schema.StringAttribute{Required: true, MarkdownDescription: "Test type (e.g. SystemResource, ProcessMemory)."},
			"condition": schema.StringAttribute{Required: true, MarkdownDescription: "Monit condition expression."},
			"action":    schema.StringAttribute{Required: true, MarkdownDescription: "Action on match (alert, restart, stop, exec, ...)."},
			"path":      schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Path/program for exec action.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}
