// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package monit

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// TestResourceModel is the Terraform state model for opnsense_monit_test.
type TestResourceModel struct {
	ID        types.String `tfsdk:"id"`
	Name      types.String `tfsdk:"name"`
	Type      types.String `tfsdk:"type"`
	Condition types.String `tfsdk:"condition"`
	Action    types.String `tfsdk:"action"`
	Path      types.String `tfsdk:"path"`
}

type testAPIResponse struct {
	Name      string               `json:"name"`
	Type      opnsense.SelectedMap `json:"type"`
	Condition string               `json:"condition"`
	Action    opnsense.SelectedMap `json:"action"`
	Path      string               `json:"path"`
}

type testAPIRequest struct {
	Name      string `json:"name"`
	Type      string `json:"type"`
	Condition string `json:"condition"`
	Action    string `json:"action"`
	Path      string `json:"path,omitempty"`
}

func (m *TestResourceModel) toAPI(_ context.Context) *testAPIRequest {
	return &testAPIRequest{
		Name:      m.Name.ValueString(),
		Type:      m.Type.ValueString(),
		Condition: m.Condition.ValueString(),
		Action:    m.Action.ValueString(),
		Path:      m.Path.ValueString(),
	}
}

func (m *TestResourceModel) fromAPI(_ context.Context, a *testAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Name = types.StringValue(a.Name)
	m.Type = types.StringValue(string(a.Type))
	m.Condition = types.StringValue(a.Condition)
	m.Action = types.StringValue(string(a.Action))
	m.Path = types.StringValue(a.Path)
}
