// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package cron_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccJob_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_cron_job", opnsense.ReqOpts{GetEndpoint: "/api/cron/settings/get_job", Monad: "job"}),
		Steps: []resource.TestStep{
			{
				Config: testAccJobConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_cron_job.test", "id"),
			},
			{ResourceName: "opnsense_cron_job.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccJobConfig = `

resource "opnsense_cron_job" "test" {
  command = "cron restart"
  description = "tf-acc-cron"
}
`
