// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package cron

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &jobDataSource{}

type jobDataSource struct{ client *opnsense.Client }

func newJobDataSource() datasource.DataSource { return &jobDataSource{} }

func (d *jobDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_cron_job"
}

func (d *jobDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Look up an existing a cron job on OPNsense by UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID of the a cron job to look up.",
			},
			"enabled":     dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether this job is enabled."},
			"minutes":     dsschema.StringAttribute{Computed: true, MarkdownDescription: "Minutes field (cron syntax)."},
			"hours":       dsschema.StringAttribute{Computed: true, MarkdownDescription: "Hours field (cron syntax)."},
			"days":        dsschema.StringAttribute{Computed: true, MarkdownDescription: "Day-of-month field (cron syntax)."},
			"months":      dsschema.StringAttribute{Computed: true, MarkdownDescription: "Month field (cron syntax)."},
			"weekdays":    dsschema.StringAttribute{Computed: true, MarkdownDescription: "Day-of-week field (cron syntax)."},
			"who":         dsschema.StringAttribute{Computed: true, MarkdownDescription: "User the job runs as."},
			"command":     dsschema.StringAttribute{Computed: true, MarkdownDescription: "Configd action to run."},
			"parameters":  dsschema.StringAttribute{Computed: true, MarkdownDescription: "Parameters passed to the command."},
			"description": dsschema.StringAttribute{Computed: true, MarkdownDescription: "Description."},
		},
	}
}

func (d *jobDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *jobDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config JobResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[jobAPIResponse](ctx, d.client, jobReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a cron job", fmt.Sprintf("Could not read a cron job %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
