// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package syslog

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/tfconv"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// DestinationResourceModel is the Terraform state model for opnsense_syslog_destination.
type DestinationResourceModel struct {
	ID          types.String `tfsdk:"id"`
	Enabled     types.Bool   `tfsdk:"enabled"`
	Transport   types.String `tfsdk:"transport"`
	Hostname    types.String `tfsdk:"hostname"`
	Port        types.Int64  `tfsdk:"port"`
	Level       types.Set    `tfsdk:"level"`
	Facility    types.Set    `tfsdk:"facility"`
	Certificate types.String `tfsdk:"certificate"`
	RFC5424     types.Bool   `tfsdk:"rfc5424"`
	Description types.String `tfsdk:"description"`
}

type destinationAPIResponse struct {
	Enabled     string                   `json:"enabled"`
	Transport   opnsense.SelectedMap     `json:"transport"`
	Hostname    string                   `json:"hostname"`
	Port        string                   `json:"port"`
	Level       opnsense.SelectedMapList `json:"level"`
	Facility    opnsense.SelectedMapList `json:"facility"`
	Certificate opnsense.SelectedMap     `json:"certificate"`
	RFC5424     string                   `json:"rfc5424"`
	Description string                   `json:"description"`
}

type destinationAPIRequest struct {
	Enabled     string `json:"enabled"`
	Transport   string `json:"transport"`
	Hostname    string `json:"hostname"`
	Port        string `json:"port,omitempty"`
	Level       string `json:"level,omitempty"`
	Facility    string `json:"facility,omitempty"`
	Certificate string `json:"certificate,omitempty"`
	RFC5424     string `json:"rfc5424"`
	Description string `json:"description,omitempty"`
}

func (m *DestinationResourceModel) toAPI(ctx context.Context) *destinationAPIRequest {
	return &destinationAPIRequest{
		Enabled:     opnsense.BoolToString(m.Enabled.ValueBool()),
		Transport:   m.Transport.ValueString(),
		Hostname:    m.Hostname.ValueString(),
		Port:        tfconv.IntOrEmpty(m.Port.ValueInt64()),
		Level:       tfconv.SetToCSV(ctx, m.Level),
		Facility:    tfconv.SetToCSV(ctx, m.Facility),
		Certificate: m.Certificate.ValueString(),
		RFC5424:     opnsense.BoolToString(m.RFC5424.ValueBool()),
		Description: m.Description.ValueString(),
	}
}

func (m *DestinationResourceModel) fromAPI(_ context.Context, a *destinationAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Enabled = types.BoolValue(opnsense.StringToBool(a.Enabled))
	m.Transport = types.StringValue(string(a.Transport))
	m.Hostname = types.StringValue(a.Hostname)
	m.Port = types.Int64Value(tfconv.IntOrZero(a.Port))
	m.Level = tfconv.SliceToSet(a.Level)
	m.Facility = tfconv.SliceToSet(a.Facility)
	m.Certificate = types.StringValue(string(a.Certificate))
	m.RFC5424 = types.BoolValue(opnsense.StringToBool(a.RFC5424))
	m.Description = types.StringValue(a.Description)
}
