// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package syslog_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccDestination_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_syslog_destination", opnsense.ReqOpts{GetEndpoint: "/api/syslog/settings/get_destination", Monad: "destination"}),
		Steps: []resource.TestStep{
			{
				Config: testAccDestinationConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_syslog_destination.test", "id"),
			},
			{ResourceName: "opnsense_syslog_destination.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccDestinationConfig = `
resource "opnsense_syslog_destination" "test" {
  transport = "udp4"
  hostname = "192.0.2.1"
}
`
