// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package syslog

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &destinationDataSource{}

type destinationDataSource struct{ client *opnsense.Client }

func newDestinationDataSource() datasource.DataSource { return &destinationDataSource{} }

func (d *destinationDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_syslog_destination"
}

func (d *destinationDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Look up an existing a syslog destination on OPNsense by UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID of the a syslog destination to look up.",
			},
			"enabled":     dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether this destination is enabled."},
			"transport":   dsschema.StringAttribute{Computed: true, MarkdownDescription: "Transport: udp4, tcp4, udp6, tcp6, tls4, tls6."},
			"hostname":    dsschema.StringAttribute{Computed: true, MarkdownDescription: "Destination hostname or IP."},
			"port":        dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Destination port."},
			"level":       dsschema.SetAttribute{ElementType: types.StringType, Computed: true, MarkdownDescription: "Log levels to forward (e.g. info, warn, error)."},
			"facility":    dsschema.SetAttribute{ElementType: types.StringType, Computed: true, MarkdownDescription: "Syslog facilities to forward (empty = all)."},
			"certificate": dsschema.StringAttribute{Computed: true, MarkdownDescription: "Certificate reference for TLS transports."},
			"rfc5424":     dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Use RFC 5424 message format."},
			"description": dsschema.StringAttribute{Computed: true, MarkdownDescription: "Description."},
		},
	}
}

func (d *destinationDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *destinationDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config DestinationResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[destinationAPIResponse](ctx, d.client, destinationReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a syslog destination", fmt.Sprintf("Could not read a syslog destination %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
