// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package kea_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
)

func TestAccCtrlAgent_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		Steps: []resource.TestStep{
			{
				Config: testAccCtrlAgentConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_kea_ctrl_agent.test", "id"),
			},
			{ResourceName: "opnsense_kea_ctrl_agent.test", ImportState: true, ImportStateId: "kea-ctrl-agent", ImportStateVerify: true},
		},
	})
}

const testAccCtrlAgentConfig = `

resource "opnsense_kea_ctrl_agent" "test" {
}
`
