// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package kea

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// CtrlAgentResourceModel is the Terraform state model for opnsense_kea_ctrl_agent.
type CtrlAgentResourceModel struct {
	ID       types.String `tfsdk:"id"`
	Enabled  types.Bool   `tfsdk:"enabled"`
	HTTPHost types.String `tfsdk:"http_host"`
	HTTPPort types.String `tfsdk:"http_port"`
}

type ctrlAgentAPIResponse struct {
	Enabled  string `json:"enabled"`
	HTTPHost string `json:"http_host"`
	HTTPPort string `json:"http_port"`
}

type ctrlAgentAPIRequest struct {
	Enabled  string `json:"enabled"`
	HTTPHost string `json:"http_host,omitempty"`
	HTTPPort string `json:"http_port,omitempty"`
}

func (m *CtrlAgentResourceModel) toAPI(_ context.Context) *ctrlAgentAPIRequest {
	return &ctrlAgentAPIRequest{
		Enabled:  opnsense.BoolToString(m.Enabled.ValueBool()),
		HTTPHost: m.HTTPHost.ValueString(),
		HTTPPort: m.HTTPPort.ValueString(),
	}
}

func (m *CtrlAgentResourceModel) fromAPI(_ context.Context, a *ctrlAgentAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Enabled = types.BoolValue(opnsense.StringToBool(a.Enabled))
	m.HTTPHost = types.StringValue(a.HTTPHost)
	m.HTTPPort = types.StringValue(a.HTTPPort)
}
