// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package kea

import (
	"context"
	"errors"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var (
	_ resource.Resource                = &ctrlAgentResource{}
	_ resource.ResourceWithImportState = &ctrlAgentResource{}
)

// ctrlAgentID is the synthetic identifier for this singleton settings object.
const ctrlAgentID = "kea-ctrl-agent"

var ctrlAgentReqOpts = opnsense.ReqOpts{
	GetEndpoint:         "/api/kea/ctrl_agent/get",
	UpdateEndpoint:      "/api/kea/ctrl_agent/set",
	ReconfigureEndpoint: "/api/kea/service/reconfigure",
	Monad:               "ctrlagent.general",
}

type ctrlAgentResource struct{ client *opnsense.Client }

func newCtrlAgentResource() resource.Resource { return &ctrlAgentResource{} }

func (r *ctrlAgentResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_kea_ctrl_agent"
}

func (r *ctrlAgentResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	r.client = client
}

func (r *ctrlAgentResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan CtrlAgentResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := opnsense.UpdateSingleton(ctx, r.client, ctrlAgentReqOpts, plan.toAPI(ctx)); err != nil {
		resp.Diagnostics.AddError("Error applying the Kea DHCP control agent settings", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.GetSingleton[ctrlAgentAPIResponse](ctx, r.client, ctrlAgentReqOpts)
	if err != nil {
		resp.Diagnostics.AddError("Error reading the Kea DHCP control agent settings after apply", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, ctrlAgentID)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ctrlAgentResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state CtrlAgentResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	result, err := opnsense.GetSingleton[ctrlAgentAPIResponse](ctx, r.client, ctrlAgentReqOpts)
	if err != nil {
		var nf *opnsense.NotFoundError
		if errors.As(err, &nf) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading the Kea DHCP control agent settings", fmt.Sprintf("%s", err))
		return
	}
	state.fromAPI(ctx, result, ctrlAgentID)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *ctrlAgentResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan CtrlAgentResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := opnsense.UpdateSingleton(ctx, r.client, ctrlAgentReqOpts, plan.toAPI(ctx)); err != nil {
		resp.Diagnostics.AddError("Error updating the Kea DHCP control agent settings", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.GetSingleton[ctrlAgentAPIResponse](ctx, r.client, ctrlAgentReqOpts)
	if err != nil {
		resp.Diagnostics.AddError("Error reading the Kea DHCP control agent settings after update", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, ctrlAgentID)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// Delete is a no-op for the singleton; destroy only removes it from state.
func (r *ctrlAgentResource) Delete(_ context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse) {
}

func (r *ctrlAgentResource) ImportState(ctx context.Context, _ resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), types.StringValue(ctrlAgentID))...)
}
