// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package kea

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/tfconv"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// DHCPv6SettingsResourceModel is the Terraform state model for opnsense_kea_dhcpv6_settings.
type DHCPv6SettingsResourceModel struct {
	ID             types.String `tfsdk:"id"`
	Enabled        types.Bool   `tfsdk:"enabled"`
	ManualConfig   types.Bool   `tfsdk:"manual_config"`
	Interfaces     types.Set    `tfsdk:"interfaces"`
	ValidLifetime  types.Int64  `tfsdk:"valid_lifetime"`
	FirewallRules  types.Bool   `tfsdk:"firewall_rules"`
	DHCPSocketType types.String `tfsdk:"dhcp_socket_type"`
}

type dhcpv6SettingsAPIResponse struct {
	Enabled        string                   `json:"enabled"`
	ManualConfig   string                   `json:"manual_config"`
	Interfaces     opnsense.SelectedMapList `json:"interfaces"`
	ValidLifetime  string                   `json:"valid_lifetime"`
	FirewallRules  string                   `json:"fwrules"`
	DHCPSocketType opnsense.SelectedMap     `json:"dhcp_socket_type"`
}

type dhcpv6SettingsAPIRequest struct {
	Enabled        string `json:"enabled"`
	ManualConfig   string `json:"manual_config"`
	Interfaces     string `json:"interfaces,omitempty"`
	ValidLifetime  string `json:"valid_lifetime,omitempty"`
	FirewallRules  string `json:"fwrules"`
	DHCPSocketType string `json:"dhcp_socket_type,omitempty"`
}

func (m *DHCPv6SettingsResourceModel) toAPI(ctx context.Context) *dhcpv6SettingsAPIRequest {
	return &dhcpv6SettingsAPIRequest{
		Enabled:        opnsense.BoolToString(m.Enabled.ValueBool()),
		ManualConfig:   opnsense.BoolToString(m.ManualConfig.ValueBool()),
		Interfaces:     tfconv.SetToCSV(ctx, m.Interfaces),
		ValidLifetime:  tfconv.IntOrEmpty(m.ValidLifetime.ValueInt64()),
		FirewallRules:  opnsense.BoolToString(m.FirewallRules.ValueBool()),
		DHCPSocketType: m.DHCPSocketType.ValueString(),
	}
}

func (m *DHCPv6SettingsResourceModel) fromAPI(_ context.Context, a *dhcpv6SettingsAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Enabled = types.BoolValue(opnsense.StringToBool(a.Enabled))
	m.ManualConfig = types.BoolValue(opnsense.StringToBool(a.ManualConfig))
	m.Interfaces = tfconv.SliceToSet(a.Interfaces)
	m.ValidLifetime = types.Int64Value(tfconv.IntOrZero(a.ValidLifetime))
	m.FirewallRules = types.BoolValue(opnsense.StringToBool(a.FirewallRules))
	m.DHCPSocketType = types.StringValue(string(a.DHCPSocketType))
}
