// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package kea

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *dhcpv6SettingsResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages the Kea DHCPv6 general settings on OPNsense.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource identifier.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"enabled":          schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Enable the Kea DHCPv6 server."},
			"manual_config":    schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Manage the Kea config file manually (disable GUI management)."},
			"interfaces":       schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, MarkdownDescription: "Interfaces the DHCPv6 server listens on."},
			"valid_lifetime":   schema.Int64Attribute{Optional: true, Computed: true, MarkdownDescription: "Default lease valid lifetime in seconds.", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"firewall_rules":   schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(true), MarkdownDescription: "Automatically add firewall rules for the service."},
			"dhcp_socket_type": schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "DHCP socket type: raw or udp.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}
