// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package kea

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// HAPeerResourceModel is the Terraform state model for opnsense_kea_ha_peer.
type HAPeerResourceModel struct {
	ID   types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
	Role types.String `tfsdk:"role"`
	URL  types.String `tfsdk:"url"`
}

type haPeerAPIResponse struct {
	Name string               `json:"name"`
	Role opnsense.SelectedMap `json:"role"`
	URL  string               `json:"url"`
}

type haPeerAPIRequest struct {
	Name string `json:"name"`
	Role string `json:"role,omitempty"`
	URL  string `json:"url"`
}

func (m *HAPeerResourceModel) toAPI(_ context.Context) *haPeerAPIRequest {
	return &haPeerAPIRequest{
		Name: m.Name.ValueString(),
		Role: m.Role.ValueString(),
		URL:  m.URL.ValueString(),
	}
}

func (m *HAPeerResourceModel) fromAPI(_ context.Context, a *haPeerAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Name = types.StringValue(a.Name)
	m.Role = types.StringValue(string(a.Role))
	m.URL = types.StringValue(a.URL)
}
