// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package kea_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccHAPeer_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_kea_ha_peer", opnsense.ReqOpts{GetEndpoint: "/api/kea/dhcpv4/getPeer", Monad: "peer"}),
		Steps: []resource.TestStep{
			{
				Config: testAccHAPeerConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_kea_ha_peer.test", "id"),
			},
			{ResourceName: "opnsense_kea_ha_peer.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccHAPeerConfig = `

resource "opnsense_kea_ha_peer" "test" {
  name = "tfaccpeer"
  url = "http://192.0.2.5:8000/"
}
`
