// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package kea

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &haPeerDataSource{}

type haPeerDataSource struct{ client *opnsense.Client }

func newHAPeerDataSource() datasource.DataSource { return &haPeerDataSource{} }

func (d *haPeerDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_kea_ha_peer"
}

func (d *haPeerDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Look up an existing a Kea High Availability peer on OPNsense by UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID of the a Kea High Availability peer to look up.",
			},
			"name": dsschema.StringAttribute{Computed: true, MarkdownDescription: "Unique name of the HA peer (must match the server name)."},
			"role": dsschema.StringAttribute{Computed: true, MarkdownDescription: "HA role: primary or standby."},
			"url":  dsschema.StringAttribute{Computed: true, MarkdownDescription: "Control-agent URL of the peer."},
		},
	}
}

func (d *haPeerDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *haPeerDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config HAPeerResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[haPeerAPIResponse](ctx, d.client, haPeerReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading a Kea High Availability peer", fmt.Sprintf("Could not read a Kea High Availability peer %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
