// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &ospfPrefixlistDataSource{}

type ospfPrefixlistDataSource struct{ client *opnsense.Client }

func newOSPFPrefixListDataSource() datasource.DataSource { return &ospfPrefixlistDataSource{} }

func (d *ospfPrefixlistDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_quagga_ospf_prefixlist"
}

func (d *ospfPrefixlistDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Look up an existing an OSPF prefix list on OPNsense by UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID of the an OSPF prefix list to look up.",
			},
			"enabled":    dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether this entry is enabled."},
			"name":       dsschema.StringAttribute{Computed: true, MarkdownDescription: "Prefix list name."},
			"seq_number": dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Sequence number."},
			"action":     dsschema.StringAttribute{Computed: true, MarkdownDescription: "Action: permit or deny."},
			"network":    dsschema.StringAttribute{Computed: true, MarkdownDescription: "Network/CIDR to match."},
		},
	}
}

func (d *ospfPrefixlistDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *ospfPrefixlistDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config OSPFPrefixListResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[ospfPrefixlistAPIResponse](ctx, d.client, ospfPrefixlistReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading an OSPF prefix list", fmt.Sprintf("Could not read an OSPF prefix list %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
