// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/tfconv"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// OSPFNeighborResourceModel is the Terraform state model for opnsense_quagga_ospf_neighbor.
type OSPFNeighborResourceModel struct {
	ID           types.String `tfsdk:"id"`
	Enabled      types.Bool   `tfsdk:"enabled"`
	Description  types.String `tfsdk:"description"`
	Address      types.String `tfsdk:"address"`
	PollInterval types.Int64  `tfsdk:"poll_interval"`
	Priority     types.Int64  `tfsdk:"priority"`
}

type ospfNeighborAPIResponse struct {
	Enabled      string `json:"enabled"`
	Description  string `json:"description"`
	Address      string `json:"address"`
	PollInterval string `json:"pollinterval"`
	Priority     string `json:"priority"`
}

type ospfNeighborAPIRequest struct {
	Enabled      string `json:"enabled"`
	Description  string `json:"description,omitempty"`
	Address      string `json:"address"`
	PollInterval string `json:"pollinterval,omitempty"`
	Priority     string `json:"priority,omitempty"`
}

func (m *OSPFNeighborResourceModel) toAPI(_ context.Context) *ospfNeighborAPIRequest {
	return &ospfNeighborAPIRequest{
		Enabled:      opnsense.BoolToString(m.Enabled.ValueBool()),
		Description:  m.Description.ValueString(),
		Address:      m.Address.ValueString(),
		PollInterval: tfconv.IntOrEmpty(m.PollInterval.ValueInt64()),
		Priority:     tfconv.IntOrEmpty(m.Priority.ValueInt64()),
	}
}

func (m *OSPFNeighborResourceModel) fromAPI(_ context.Context, a *ospfNeighborAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Enabled = types.BoolValue(opnsense.StringToBool(a.Enabled))
	m.Description = types.StringValue(a.Description)
	m.Address = types.StringValue(a.Address)
	m.PollInterval = types.Int64Value(tfconv.IntOrZero(a.PollInterval))
	m.Priority = types.Int64Value(tfconv.IntOrZero(a.Priority))
}
