// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/tfconv"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// OSPF6NetworkResourceModel is the Terraform state model for opnsense_quagga_ospf6_network.
type OSPF6NetworkResourceModel struct {
	ID        types.String `tfsdk:"id"`
	Enabled   types.Bool   `tfsdk:"enabled"`
	IPAddress types.String `tfsdk:"ip_address"`
	Netmask   types.Int64  `tfsdk:"netmask"`
	Area      types.String `tfsdk:"area"`
	AreaRange types.String `tfsdk:"area_range"`
}

type ospf6NetworkAPIResponse struct {
	Enabled   string `json:"enabled"`
	IPAddress string `json:"ipaddr"`
	Netmask   string `json:"netmask"`
	Area      string `json:"area"`
	AreaRange string `json:"arearange"`
}

type ospf6NetworkAPIRequest struct {
	Enabled   string `json:"enabled"`
	IPAddress string `json:"ipaddr"`
	Netmask   string `json:"netmask"`
	Area      string `json:"area"`
	AreaRange string `json:"arearange,omitempty"`
}

func (m *OSPF6NetworkResourceModel) toAPI(_ context.Context) *ospf6NetworkAPIRequest {
	return &ospf6NetworkAPIRequest{
		Enabled:   opnsense.BoolToString(m.Enabled.ValueBool()),
		IPAddress: m.IPAddress.ValueString(),
		Netmask:   opnsense.Int64ToString(m.Netmask.ValueInt64()),
		Area:      m.Area.ValueString(),
		AreaRange: m.AreaRange.ValueString(),
	}
}

func (m *OSPF6NetworkResourceModel) fromAPI(_ context.Context, a *ospf6NetworkAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Enabled = types.BoolValue(opnsense.StringToBool(a.Enabled))
	m.IPAddress = types.StringValue(a.IPAddress)
	m.Netmask = types.Int64Value(tfconv.IntOrZero(a.Netmask))
	m.Area = types.StringValue(a.Area)
	m.AreaRange = types.StringValue(a.AreaRange)
}
