// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &ospf6NetworkDataSource{}

type ospf6NetworkDataSource struct{ client *opnsense.Client }

func newOSPF6NetworkDataSource() datasource.DataSource { return &ospf6NetworkDataSource{} }

func (d *ospf6NetworkDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_quagga_ospf6_network"
}

func (d *ospf6NetworkDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Look up an existing an OSPFv3 network on OPNsense by UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID of the an OSPFv3 network to look up.",
			},
			"enabled":    dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether this network is enabled."},
			"ip_address": dsschema.StringAttribute{Computed: true, MarkdownDescription: "Network address."},
			"netmask":    dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Netmask bits."},
			"area":       dsschema.StringAttribute{Computed: true, MarkdownDescription: "OSPFv3 area."},
			"area_range": dsschema.StringAttribute{Computed: true, MarkdownDescription: "Optional area range summarization."},
		},
	}
}

func (d *ospf6NetworkDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *ospf6NetworkDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config OSPF6NetworkResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[ospf6NetworkAPIResponse](ctx, d.client, ospf6NetworkReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading an OSPFv3 network", fmt.Sprintf("Could not read an OSPFv3 network %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
