// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccOSPF6Redistribution_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_quagga_ospf6_redistribution", opnsense.ReqOpts{GetEndpoint: "/api/quagga/ospf6settings/get_redistribution", Monad: "redistribution"}),
		Steps: []resource.TestStep{
			{
				Config: testAccOSPF6RedistributionConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_quagga_ospf6_redistribution.test", "id"),
			},
			{ResourceName: "opnsense_quagga_ospf6_redistribution.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccOSPF6RedistributionConfig = `
resource "opnsense_quagga_ospf6_redistribution" "test" {
  redistribute = "test"
}
`
