// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga

import (
	"context"
	"errors"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var (
	_ resource.Resource                = &ospfRoutemapResource{}
	_ resource.ResourceWithImportState = &ospfRoutemapResource{}
)

var ospfRoutemapReqOpts = opnsense.ReqOpts{
	AddEndpoint:         "/api/quagga/ospfsettings/add_routemap",
	GetEndpoint:         "/api/quagga/ospfsettings/get_routemap",
	UpdateEndpoint:      "/api/quagga/ospfsettings/set_routemap",
	DeleteEndpoint:      "/api/quagga/ospfsettings/del_routemap",
	SearchEndpoint:      "/api/quagga/ospfsettings/search_routemap",
	ReconfigureEndpoint: "/api/quagga/service/reconfigure",
	Monad:               "routemap",
}

type ospfRoutemapResource struct{ client *opnsense.Client }

func newOSPFRouteMapResource() resource.Resource { return &ospfRoutemapResource{} }

func (r *ospfRoutemapResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_quagga_ospf_routemap"
}

func (r *ospfRoutemapResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	r.client = client
}

func (r *ospfRoutemapResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan OSPFRouteMapResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	uuid, err := opnsense.Add(ctx, r.client, ospfRoutemapReqOpts, plan.toAPI(ctx))
	if err != nil {
		resp.Diagnostics.AddError("Error creating an OSPF route map", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.Get[ospfRoutemapAPIResponse](ctx, r.client, ospfRoutemapReqOpts, uuid)
	if err != nil {
		resp.Diagnostics.AddError("Error reading an OSPF route map after create", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, uuid)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ospfRoutemapResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state OSPFRouteMapResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	result, err := opnsense.Get[ospfRoutemapAPIResponse](ctx, r.client, ospfRoutemapReqOpts, state.ID.ValueString())
	if err != nil {
		var nf *opnsense.NotFoundError
		if errors.As(err, &nf) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading an OSPF route map", fmt.Sprintf("%s", err))
		return
	}
	state.fromAPI(ctx, result, state.ID.ValueString())
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *ospfRoutemapResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state OSPFRouteMapResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()
	if err := opnsense.Update(ctx, r.client, ospfRoutemapReqOpts, plan.toAPI(ctx), id); err != nil {
		resp.Diagnostics.AddError("Error updating an OSPF route map", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.Get[ospfRoutemapAPIResponse](ctx, r.client, ospfRoutemapReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading an OSPF route map after update", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ospfRoutemapResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state OSPFRouteMapResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := opnsense.Delete(ctx, r.client, ospfRoutemapReqOpts, state.ID.ValueString()); err != nil {
		var nf *opnsense.NotFoundError
		if errors.As(err, &nf) {
			return
		}
		resp.Diagnostics.AddError("Error deleting an OSPF route map", fmt.Sprintf("%s", err))
	}
}

func (r *ospfRoutemapResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
