// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &ospf6InterfaceDataSource{}

type ospf6InterfaceDataSource struct{ client *opnsense.Client }

func newOSPF6InterfaceDataSource() datasource.DataSource { return &ospf6InterfaceDataSource{} }

func (d *ospf6InterfaceDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_quagga_ospf6_interface"
}

func (d *ospf6InterfaceDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Reads an OSPFv3 interface on OPNsense by its UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID to look up.",
			},
			"enabled":        dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether this interface config is enabled."},
			"interface":      dsschema.StringAttribute{Computed: true, MarkdownDescription: "Interface name."},
			"area":           dsschema.StringAttribute{Computed: true, MarkdownDescription: "OSPFv3 area."},
			"passive":        dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Mark interface passive."},
			"cost":           dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Interface cost (0 = auto)."},
			"hello_interval": dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Hello interval in seconds (0 = default)."},
			"dead_interval":  dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Dead interval in seconds (0 = default)."},
			"priority":       dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Router priority (0 = default)."},
			"network_type":   dsschema.StringAttribute{Computed: true, MarkdownDescription: "OSPFv3 network type."},
			"bfd":            dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Enable BFD on this interface."},
		},
	}
}

func (d *ospf6InterfaceDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *ospf6InterfaceDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config OSPF6InterfaceResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[ospf6InterfaceAPIResponse](ctx, d.client, ospf6InterfaceReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading an OSPFv3 interface", fmt.Sprintf("Could not read an OSPFv3 interface %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
