// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccOSPF6PrefixList_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { preCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_quagga_ospf6_prefixlist", opnsense.ReqOpts{GetEndpoint: "/api/quagga/ospf6settings/get_prefixlist", Monad: "prefixlist"}),
		Steps: []resource.TestStep{
			{
				Config: testAccOSPF6PrefixListConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_quagga_ospf6_prefixlist.test", "id"),
			},
			{ResourceName: "opnsense_quagga_ospf6_prefixlist.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccOSPF6PrefixListConfig = `

resource "opnsense_quagga_ospf6_prefixlist" "test" {
  name = "test"
  seq_number = 1
  action = "test"
  network = "test"
}
`
