// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccOSPFInterface_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_quagga_ospf_interface", opnsense.ReqOpts{GetEndpoint: "/api/quagga/ospfsettings/get_interface", Monad: "interface"}),
		Steps: []resource.TestStep{
			{
				Config: testAccOSPFInterfaceConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_quagga_ospf_interface.test", "id"),
			},
			{ResourceName: "opnsense_quagga_ospf_interface.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccOSPFInterfaceConfig = `
resource "opnsense_quagga_ospf_interface" "test" {
}
`
