// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga

import (
	"context"
	"errors"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var (
	_ resource.Resource                = &ospf6RedistributionResource{}
	_ resource.ResourceWithImportState = &ospf6RedistributionResource{}
)

var ospf6RedistributionReqOpts = opnsense.ReqOpts{
	AddEndpoint:         "/api/quagga/ospf6settings/add_redistribution",
	GetEndpoint:         "/api/quagga/ospf6settings/get_redistribution",
	UpdateEndpoint:      "/api/quagga/ospf6settings/set_redistribution",
	DeleteEndpoint:      "/api/quagga/ospf6settings/del_redistribution",
	SearchEndpoint:      "/api/quagga/ospf6settings/search_redistribution",
	ReconfigureEndpoint: "/api/quagga/service/reconfigure",
	Monad:               "redistribution",
}

type ospf6RedistributionResource struct{ client *opnsense.Client }

func newOSPF6RedistributionResource() resource.Resource { return &ospf6RedistributionResource{} }

func (r *ospf6RedistributionResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_quagga_ospf6_redistribution"
}

func (r *ospf6RedistributionResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	r.client = client
}

func (r *ospf6RedistributionResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan OSPF6RedistributionResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	uuid, err := opnsense.Add(ctx, r.client, ospf6RedistributionReqOpts, plan.toAPI(ctx))
	if err != nil {
		resp.Diagnostics.AddError("Error creating an OSPFv3 redistribution", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.Get[ospf6RedistributionAPIResponse](ctx, r.client, ospf6RedistributionReqOpts, uuid)
	if err != nil {
		resp.Diagnostics.AddError("Error reading an OSPFv3 redistribution after create", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, uuid)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ospf6RedistributionResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state OSPF6RedistributionResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	result, err := opnsense.Get[ospf6RedistributionAPIResponse](ctx, r.client, ospf6RedistributionReqOpts, state.ID.ValueString())
	if err != nil {
		var nf *opnsense.NotFoundError
		if errors.As(err, &nf) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading an OSPFv3 redistribution", fmt.Sprintf("%s", err))
		return
	}
	state.fromAPI(ctx, result, state.ID.ValueString())
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *ospf6RedistributionResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state OSPF6RedistributionResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()
	if err := opnsense.Update(ctx, r.client, ospf6RedistributionReqOpts, plan.toAPI(ctx), id); err != nil {
		resp.Diagnostics.AddError("Error updating an OSPFv3 redistribution", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.Get[ospf6RedistributionAPIResponse](ctx, r.client, ospf6RedistributionReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading an OSPFv3 redistribution after update", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ospf6RedistributionResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state OSPF6RedistributionResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := opnsense.Delete(ctx, r.client, ospf6RedistributionReqOpts, state.ID.ValueString()); err != nil {
		var nf *opnsense.NotFoundError
		if errors.As(err, &nf) {
			return
		}
		resp.Diagnostics.AddError("Error deleting an OSPFv3 redistribution", fmt.Sprintf("%s", err))
	}
}

func (r *ospf6RedistributionResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
