// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccOSPF6Network_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { preCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_quagga_ospf6_network", opnsense.ReqOpts{GetEndpoint: "/api/quagga/ospf6settings/get_network", Monad: "network"}),
		Steps: []resource.TestStep{
			{
				Config: testAccOSPF6NetworkConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_quagga_ospf6_network.test", "id"),
			},
			{ResourceName: "opnsense_quagga_ospf6_network.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccOSPF6NetworkConfig = `

resource "opnsense_quagga_ospf6_network" "test" {
  ip_address = "test"
  netmask = 1
  area = "test"
}
`
