// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga

import (
	"context"
	"errors"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var (
	_ resource.Resource                = &ospfPrefixlistResource{}
	_ resource.ResourceWithImportState = &ospfPrefixlistResource{}
)

var ospfPrefixlistReqOpts = opnsense.ReqOpts{
	AddEndpoint:         "/api/quagga/ospfsettings/add_prefixlist",
	GetEndpoint:         "/api/quagga/ospfsettings/get_prefixlist",
	UpdateEndpoint:      "/api/quagga/ospfsettings/set_prefixlist",
	DeleteEndpoint:      "/api/quagga/ospfsettings/del_prefixlist",
	SearchEndpoint:      "/api/quagga/ospfsettings/search_prefixlist",
	ReconfigureEndpoint: "/api/quagga/service/reconfigure",
	Monad:               "prefixlist",
}

type ospfPrefixlistResource struct{ client *opnsense.Client }

func newOSPFPrefixListResource() resource.Resource { return &ospfPrefixlistResource{} }

func (r *ospfPrefixlistResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_quagga_ospf_prefixlist"
}

func (r *ospfPrefixlistResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	r.client = client
}

func (r *ospfPrefixlistResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan OSPFPrefixListResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	uuid, err := opnsense.Add(ctx, r.client, ospfPrefixlistReqOpts, plan.toAPI(ctx))
	if err != nil {
		resp.Diagnostics.AddError("Error creating an OSPF prefix list", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.Get[ospfPrefixlistAPIResponse](ctx, r.client, ospfPrefixlistReqOpts, uuid)
	if err != nil {
		resp.Diagnostics.AddError("Error reading an OSPF prefix list after create", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, uuid)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ospfPrefixlistResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state OSPFPrefixListResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	result, err := opnsense.Get[ospfPrefixlistAPIResponse](ctx, r.client, ospfPrefixlistReqOpts, state.ID.ValueString())
	if err != nil {
		var nf *opnsense.NotFoundError
		if errors.As(err, &nf) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading an OSPF prefix list", fmt.Sprintf("%s", err))
		return
	}
	state.fromAPI(ctx, result, state.ID.ValueString())
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *ospfPrefixlistResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state OSPFPrefixListResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()
	if err := opnsense.Update(ctx, r.client, ospfPrefixlistReqOpts, plan.toAPI(ctx), id); err != nil {
		resp.Diagnostics.AddError("Error updating an OSPF prefix list", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.Get[ospfPrefixlistAPIResponse](ctx, r.client, ospfPrefixlistReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading an OSPF prefix list after update", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ospfPrefixlistResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state OSPFPrefixListResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := opnsense.Delete(ctx, r.client, ospfPrefixlistReqOpts, state.ID.ValueString()); err != nil {
		var nf *opnsense.NotFoundError
		if errors.As(err, &nf) {
			return
		}
		resp.Diagnostics.AddError("Error deleting an OSPF prefix list", fmt.Sprintf("%s", err))
	}
}

func (r *ospfPrefixlistResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
