// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// OSPFAreaResourceModel is the Terraform state model for opnsense_quagga_ospf_area.
type OSPFAreaResourceModel struct {
	ID      types.String `tfsdk:"id"`
	Enabled types.Bool   `tfsdk:"enabled"`
	AreaID  types.String `tfsdk:"area_id"`
	Type    types.String `tfsdk:"type"`
}

type ospfAreaAPIResponse struct {
	Enabled string               `json:"enabled"`
	AreaID  string               `json:"id"`
	Type    opnsense.SelectedMap `json:"type"`
}

type ospfAreaAPIRequest struct {
	Enabled string `json:"enabled"`
	AreaID  string `json:"id"`
	Type    string `json:"type"`
}

func (m *OSPFAreaResourceModel) toAPI(_ context.Context) *ospfAreaAPIRequest {
	return &ospfAreaAPIRequest{
		Enabled: opnsense.BoolToString(m.Enabled.ValueBool()),
		AreaID:  m.AreaID.ValueString(),
		Type:    m.Type.ValueString(),
	}
}

func (m *OSPFAreaResourceModel) fromAPI(_ context.Context, a *ospfAreaAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Enabled = types.BoolValue(opnsense.StringToBool(a.Enabled))
	m.AreaID = types.StringValue(a.AreaID)
	m.Type = types.StringValue(string(a.Type))
}
