// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &ospfAreaDataSource{}

type ospfAreaDataSource struct{ client *opnsense.Client }

func newOSPFAreaDataSource() datasource.DataSource { return &ospfAreaDataSource{} }

func (d *ospfAreaDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_quagga_ospf_area"
}

func (d *ospfAreaDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Reads an OSPF area on OPNsense by its UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID to look up.",
			},
			"enabled": dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether this OSPF area is enabled."},
			"area_id": dsschema.StringAttribute{Computed: true, MarkdownDescription: "OSPF area ID in dotted IPv4 format."},
			"type":    dsschema.StringAttribute{Computed: true, MarkdownDescription: "OSPF area type."},
		},
	}
}

func (d *ospfAreaDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *ospfAreaDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config OSPFAreaResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[ospfAreaAPIResponse](ctx, d.client, ospfAreaReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading an OSPF area", fmt.Sprintf("Could not read an OSPF area %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
