// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/tfconv"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// OSPFInterfaceResourceModel is the Terraform state model for opnsense_quagga_ospf_interface.
type OSPFInterfaceResourceModel struct {
	ID            types.String `tfsdk:"id"`
	Enabled       types.Bool   `tfsdk:"enabled"`
	Interface     types.String `tfsdk:"interface"`
	Area          types.String `tfsdk:"area"`
	Cost          types.Int64  `tfsdk:"cost"`
	HelloInterval types.Int64  `tfsdk:"hello_interval"`
	DeadInterval  types.Int64  `tfsdk:"dead_interval"`
	Priority      types.Int64  `tfsdk:"priority"`
	NetworkType   types.String `tfsdk:"network_type"`
	BFD           types.Bool   `tfsdk:"bfd"`
}

type ospfInterfaceAPIResponse struct {
	Enabled       string               `json:"enabled"`
	Interface     opnsense.SelectedMap `json:"interfacename"`
	Area          string               `json:"area"`
	Cost          string               `json:"cost"`
	HelloInterval string               `json:"hellointerval"`
	DeadInterval  string               `json:"deadinterval"`
	Priority      string               `json:"priority"`
	NetworkType   opnsense.SelectedMap `json:"networktype"`
	BFD           string               `json:"bfd"`
}

type ospfInterfaceAPIRequest struct {
	Enabled       string `json:"enabled"`
	Interface     string `json:"interfacename,omitempty"`
	Area          string `json:"area,omitempty"`
	Cost          string `json:"cost,omitempty"`
	HelloInterval string `json:"hellointerval,omitempty"`
	DeadInterval  string `json:"deadinterval,omitempty"`
	Priority      string `json:"priority,omitempty"`
	NetworkType   string `json:"networktype,omitempty"`
	BFD           string `json:"bfd"`
}

func (m *OSPFInterfaceResourceModel) toAPI(_ context.Context) *ospfInterfaceAPIRequest {
	return &ospfInterfaceAPIRequest{
		Enabled:       opnsense.BoolToString(m.Enabled.ValueBool()),
		Interface:     m.Interface.ValueString(),
		Area:          m.Area.ValueString(),
		Cost:          tfconv.IntOrEmpty(m.Cost.ValueInt64()),
		HelloInterval: tfconv.IntOrEmpty(m.HelloInterval.ValueInt64()),
		DeadInterval:  tfconv.IntOrEmpty(m.DeadInterval.ValueInt64()),
		Priority:      tfconv.IntOrEmpty(m.Priority.ValueInt64()),
		NetworkType:   m.NetworkType.ValueString(),
		BFD:           opnsense.BoolToString(m.BFD.ValueBool()),
	}
}

func (m *OSPFInterfaceResourceModel) fromAPI(_ context.Context, a *ospfInterfaceAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Enabled = types.BoolValue(opnsense.StringToBool(a.Enabled))
	m.Interface = types.StringValue(string(a.Interface))
	m.Area = types.StringValue(a.Area)
	m.Cost = types.Int64Value(tfconv.IntOrZero(a.Cost))
	m.HelloInterval = types.Int64Value(tfconv.IntOrZero(a.HelloInterval))
	m.DeadInterval = types.Int64Value(tfconv.IntOrZero(a.DeadInterval))
	m.Priority = types.Int64Value(tfconv.IntOrZero(a.Priority))
	m.NetworkType = types.StringValue(string(a.NetworkType))
	m.BFD = types.BoolValue(opnsense.StringToBool(a.BFD))
}
