// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &ospfRedistributionDataSource{}

type ospfRedistributionDataSource struct{ client *opnsense.Client }

func newOSPFRedistributionDataSource() datasource.DataSource { return &ospfRedistributionDataSource{} }

func (d *ospfRedistributionDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_quagga_ospf_redistribution"
}

func (d *ospfRedistributionDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Look up an existing an OSPF redistribution on OPNsense by UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID of the an OSPF redistribution to look up.",
			},
			"enabled":      dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether this redistribution is enabled."},
			"description":  dsschema.StringAttribute{Computed: true, MarkdownDescription: "Description."},
			"redistribute": dsschema.StringAttribute{Computed: true, MarkdownDescription: "Source to redistribute into OSPF."},
			"route_map":    dsschema.StringAttribute{Computed: true, MarkdownDescription: "UUID of a route map to apply."},
		},
	}
}

func (d *ospfRedistributionDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *ospfRedistributionDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config OSPFRedistributionResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[ospfRedistributionAPIResponse](ctx, d.client, ospfRedistributionReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading an OSPF redistribution", fmt.Sprintf("Could not read an OSPF redistribution %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
