// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// OSPF6PrefixListResourceModel is the Terraform state model for opnsense_quagga_ospf6_prefixlist.
type OSPF6PrefixListResourceModel struct {
	ID        types.String `tfsdk:"id"`
	Enabled   types.Bool   `tfsdk:"enabled"`
	Name      types.String `tfsdk:"name"`
	SeqNumber types.Int64  `tfsdk:"seq_number"`
	Action    types.String `tfsdk:"action"`
	Network   types.String `tfsdk:"network"`
}

type ospf6PrefixlistAPIResponse struct {
	Enabled   string               `json:"enabled"`
	Name      string               `json:"name"`
	SeqNumber string               `json:"seqnumber"`
	Action    opnsense.SelectedMap `json:"action"`
	Network   string               `json:"network"`
}

type ospf6PrefixlistAPIRequest struct {
	Enabled   string `json:"enabled"`
	Name      string `json:"name"`
	SeqNumber string `json:"seqnumber"`
	Action    string `json:"action"`
	Network   string `json:"network"`
}

func (m *OSPF6PrefixListResourceModel) toAPI(_ context.Context) *ospf6PrefixlistAPIRequest {
	return &ospf6PrefixlistAPIRequest{
		Enabled:   opnsense.BoolToString(m.Enabled.ValueBool()),
		Name:      m.Name.ValueString(),
		SeqNumber: opnsense.Int64ToString(m.SeqNumber.ValueInt64()),
		Action:    m.Action.ValueString(),
		Network:   m.Network.ValueString(),
	}
}

func (m *OSPF6PrefixListResourceModel) fromAPI(_ context.Context, a *ospf6PrefixlistAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Enabled = types.BoolValue(opnsense.StringToBool(a.Enabled))
	m.Name = types.StringValue(a.Name)
	m.SeqNumber = types.Int64Value(intOrZero(a.SeqNumber))
	m.Action = types.StringValue(string(a.Action))
	m.Network = types.StringValue(a.Network)
}
