// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &ospf6RoutemapDataSource{}

type ospf6RoutemapDataSource struct{ client *opnsense.Client }

func newOSPF6RouteMapDataSource() datasource.DataSource { return &ospf6RoutemapDataSource{} }

func (d *ospf6RoutemapDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_quagga_ospf6_routemap"
}

func (d *ospf6RoutemapDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Look up an existing an OSPFv3 route map on OPNsense by UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID of the an OSPFv3 route map to look up.",
			},
			"enabled":      dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether this route map is enabled."},
			"name":         dsschema.StringAttribute{Computed: true, MarkdownDescription: "Route map name."},
			"action":       dsschema.StringAttribute{Computed: true, MarkdownDescription: "Action: permit or deny."},
			"route_map_id": dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Order/ID."},
			"set":          dsschema.StringAttribute{Computed: true, MarkdownDescription: "Set clause."},
		},
	}
}

func (d *ospf6RoutemapDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *ospf6RoutemapDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config OSPF6RouteMapResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[ospf6RoutemapAPIResponse](ctx, d.client, ospf6RoutemapReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading an OSPFv3 route map", fmt.Sprintf("Could not read an OSPFv3 route map %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
