// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &ospf6RedistributionDataSource{}

type ospf6RedistributionDataSource struct{ client *opnsense.Client }

func newOSPF6RedistributionDataSource() datasource.DataSource {
	return &ospf6RedistributionDataSource{}
}

func (d *ospf6RedistributionDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_quagga_ospf6_redistribution"
}

func (d *ospf6RedistributionDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Reads an OSPFv3 redistribution on OPNsense by its UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID to look up.",
			},
			"enabled":      dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether this redistribution is enabled."},
			"description":  dsschema.StringAttribute{Computed: true, MarkdownDescription: "Description."},
			"redistribute": dsschema.StringAttribute{Computed: true, MarkdownDescription: "Source to redistribute into OSPFv3."},
			"route_map":    dsschema.StringAttribute{Computed: true, MarkdownDescription: "UUID of a route map to apply."},
		},
	}
}

func (d *ospf6RedistributionDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *ospf6RedistributionDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config OSPF6RedistributionResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[ospf6RedistributionAPIResponse](ctx, d.client, ospf6RedistributionReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading an OSPFv3 redistribution", fmt.Sprintf("Could not read an OSPFv3 redistribution %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
