// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccOSPFRouteMap_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { preCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_quagga_ospf_routemap", opnsense.ReqOpts{GetEndpoint: "/api/quagga/ospfsettings/get_routemap", Monad: "routemap"}),
		Steps: []resource.TestStep{
			{
				Config: testAccOSPFRouteMapConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_quagga_ospf_routemap.test", "id"),
			},
			{ResourceName: "opnsense_quagga_ospf_routemap.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccOSPFRouteMapConfig = `

resource "opnsense_quagga_ospf_routemap" "test" {
  name = "test"
  action = "permit"
}
`
