// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// OSPFRouteMapResourceModel is the Terraform state model for opnsense_quagga_ospf_routemap.
type OSPFRouteMapResourceModel struct {
	ID         types.String `tfsdk:"id"`
	Enabled    types.Bool   `tfsdk:"enabled"`
	Name       types.String `tfsdk:"name"`
	Action     types.String `tfsdk:"action"`
	RouteMapID types.Int64  `tfsdk:"route_map_id"`
	Set        types.String `tfsdk:"set"`
}

type ospfRoutemapAPIResponse struct {
	Enabled    string               `json:"enabled"`
	Name       string               `json:"name"`
	Action     opnsense.SelectedMap `json:"action"`
	RouteMapID string               `json:"id"`
	Set        string               `json:"set"`
}

type ospfRoutemapAPIRequest struct {
	Enabled    string `json:"enabled"`
	Name       string `json:"name"`
	Action     string `json:"action"`
	RouteMapID string `json:"id"`
	Set        string `json:"set"`
}

func (m *OSPFRouteMapResourceModel) toAPI(_ context.Context) *ospfRoutemapAPIRequest {
	return &ospfRoutemapAPIRequest{
		Enabled:    opnsense.BoolToString(m.Enabled.ValueBool()),
		Name:       m.Name.ValueString(),
		Action:     m.Action.ValueString(),
		RouteMapID: intOrEmpty(m.RouteMapID.ValueInt64()),
		Set:        m.Set.ValueString(),
	}
}

func (m *OSPFRouteMapResourceModel) fromAPI(_ context.Context, a *ospfRoutemapAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Enabled = types.BoolValue(opnsense.StringToBool(a.Enabled))
	m.Name = types.StringValue(a.Name)
	m.Action = types.StringValue(string(a.Action))
	m.RouteMapID = types.Int64Value(intOrZero(a.RouteMapID))
	m.Set = types.StringValue(a.Set)
}
