// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// OSPF6RedistributionResourceModel is the Terraform state model for opnsense_quagga_ospf6_redistribution.
type OSPF6RedistributionResourceModel struct {
	ID           types.String `tfsdk:"id"`
	Enabled      types.Bool   `tfsdk:"enabled"`
	Description  types.String `tfsdk:"description"`
	Redistribute types.String `tfsdk:"redistribute"`
	RouteMap     types.String `tfsdk:"route_map"`
}

type ospf6RedistributionAPIResponse struct {
	Enabled      string               `json:"enabled"`
	Description  string               `json:"description"`
	Redistribute opnsense.SelectedMap `json:"redistribute"`
	RouteMap     opnsense.SelectedMap `json:"linkedRoutemap"`
}

type ospf6RedistributionAPIRequest struct {
	Enabled      string `json:"enabled"`
	Description  string `json:"description,omitempty"`
	Redistribute string `json:"redistribute"`
	RouteMap     string `json:"linkedRoutemap,omitempty"`
}

func (m *OSPF6RedistributionResourceModel) toAPI(_ context.Context) *ospf6RedistributionAPIRequest {
	return &ospf6RedistributionAPIRequest{
		Enabled:      opnsense.BoolToString(m.Enabled.ValueBool()),
		Description:  m.Description.ValueString(),
		Redistribute: m.Redistribute.ValueString(),
		RouteMap:     m.RouteMap.ValueString(),
	}
}

func (m *OSPF6RedistributionResourceModel) fromAPI(_ context.Context, a *ospf6RedistributionAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Enabled = types.BoolValue(opnsense.StringToBool(a.Enabled))
	m.Description = types.StringValue(a.Description)
	m.Redistribute = types.StringValue(string(a.Redistribute))
	m.RouteMap = types.StringValue(string(a.RouteMap))
}
