// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &ospfRoutemapDataSource{}

type ospfRoutemapDataSource struct{ client *opnsense.Client }

func newOSPFRouteMapDataSource() datasource.DataSource { return &ospfRoutemapDataSource{} }

func (d *ospfRoutemapDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_quagga_ospf_routemap"
}

func (d *ospfRoutemapDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Reads an OSPF route map on OPNsense by its UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID to look up.",
			},
			"enabled":      dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether this route map is enabled."},
			"name":         dsschema.StringAttribute{Computed: true, MarkdownDescription: "Route map name."},
			"action":       dsschema.StringAttribute{Computed: true, MarkdownDescription: "Action: permit or deny."},
			"route_map_id": dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Order/ID (0 = unset)."},
			"set":          dsschema.StringAttribute{Computed: true, MarkdownDescription: "Set clause."},
		},
	}
}

func (d *ospfRoutemapDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *ospfRoutemapDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config OSPFRouteMapResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[ospfRoutemapAPIResponse](ctx, d.client, ospfRoutemapReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading an OSPF route map", fmt.Sprintf("Could not read an OSPF route map %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
