// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

func (r *ospf6InterfaceResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages an OSPFv3 interface on OPNsense.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource identifier.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"enabled":        schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(true), MarkdownDescription: "Whether this interface config is enabled."},
			"interface":      schema.StringAttribute{Required: true, MarkdownDescription: "Interface name."},
			"area":           schema.StringAttribute{Required: true, MarkdownDescription: "OSPFv3 area."},
			"passive":        schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Mark interface passive."},
			"cost":           schema.Int64Attribute{Optional: true, Computed: true, MarkdownDescription: "Interface cost (0 = auto).", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"hello_interval": schema.Int64Attribute{Optional: true, Computed: true, MarkdownDescription: "Hello interval in seconds (0 = default).", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"dead_interval":  schema.Int64Attribute{Optional: true, Computed: true, MarkdownDescription: "Dead interval in seconds (0 = default).", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"priority":       schema.Int64Attribute{Optional: true, Computed: true, MarkdownDescription: "Router priority (0 = default).", PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
			"network_type":   schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "OSPFv3 network type.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"bfd":            schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(false), MarkdownDescription: "Enable BFD on this interface."},
		},
	}
}
