// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccOSPFNeighbor_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_quagga_ospf_neighbor", opnsense.ReqOpts{GetEndpoint: "/api/quagga/ospfsettings/get_neighbor", Monad: "neighbor"}),
		Steps: []resource.TestStep{
			{
				Config: testAccOSPFNeighborConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_quagga_ospf_neighbor.test", "id"),
			},
			{ResourceName: "opnsense_quagga_ospf_neighbor.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccOSPFNeighborConfig = `
resource "opnsense_quagga_ospf_neighbor" "test" {
  address = "192.0.2.10"
}
`
