// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &ospf6PrefixlistDataSource{}

type ospf6PrefixlistDataSource struct{ client *opnsense.Client }

func newOSPF6PrefixListDataSource() datasource.DataSource { return &ospf6PrefixlistDataSource{} }

func (d *ospf6PrefixlistDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_quagga_ospf6_prefixlist"
}

func (d *ospf6PrefixlistDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Look up an existing an OSPFv3 prefix list on OPNsense by UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID of the an OSPFv3 prefix list to look up.",
			},
			"enabled":    dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether this entry is enabled."},
			"name":       dsschema.StringAttribute{Computed: true, MarkdownDescription: "Prefix list name."},
			"seq_number": dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Sequence number."},
			"action":     dsschema.StringAttribute{Computed: true, MarkdownDescription: "Action: permit or deny."},
			"network":    dsschema.StringAttribute{Computed: true, MarkdownDescription: "Network/CIDR to match."},
		},
	}
}

func (d *ospf6PrefixlistDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *ospf6PrefixlistDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config OSPF6PrefixListResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[ospf6PrefixlistAPIResponse](ctx, d.client, ospf6PrefixlistReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading an OSPFv3 prefix list", fmt.Sprintf("Could not read an OSPFv3 prefix list %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
