// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccOSPFNetwork_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { preCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_quagga_ospf_network", opnsense.ReqOpts{GetEndpoint: "/api/quagga/ospfsettings/get_network", Monad: "network"}),
		Steps: []resource.TestStep{
			{
				Config: testAccOSPFNetworkConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_quagga_ospf_network.test", "id"),
			},
			{ResourceName: "opnsense_quagga_ospf_network.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccOSPFNetworkConfig = `

resource "opnsense_quagga_ospf_network" "test" {
  ip_address = "192.0.2.0"
  netmask = 24
  area = "0.0.0.0"
}
`
