// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga

import (
	"context"
	"errors"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var (
	_ resource.Resource                = &ospf6InterfaceResource{}
	_ resource.ResourceWithImportState = &ospf6InterfaceResource{}
)

var ospf6InterfaceReqOpts = opnsense.ReqOpts{
	AddEndpoint:         "/api/quagga/ospf6settings/add_interface",
	GetEndpoint:         "/api/quagga/ospf6settings/get_interface",
	UpdateEndpoint:      "/api/quagga/ospf6settings/set_interface",
	DeleteEndpoint:      "/api/quagga/ospf6settings/del_interface",
	SearchEndpoint:      "/api/quagga/ospf6settings/search_interface",
	ReconfigureEndpoint: "/api/quagga/service/reconfigure",
	Monad:               "interface",
}

type ospf6InterfaceResource struct{ client *opnsense.Client }

func newOSPF6InterfaceResource() resource.Resource { return &ospf6InterfaceResource{} }

func (r *ospf6InterfaceResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_quagga_ospf6_interface"
}

func (r *ospf6InterfaceResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	r.client = client
}

func (r *ospf6InterfaceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan OSPF6InterfaceResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	uuid, err := opnsense.Add(ctx, r.client, ospf6InterfaceReqOpts, plan.toAPI(ctx))
	if err != nil {
		resp.Diagnostics.AddError("Error creating an OSPFv3 interface", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.Get[ospf6InterfaceAPIResponse](ctx, r.client, ospf6InterfaceReqOpts, uuid)
	if err != nil {
		resp.Diagnostics.AddError("Error reading an OSPFv3 interface after create", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, uuid)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ospf6InterfaceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state OSPF6InterfaceResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	result, err := opnsense.Get[ospf6InterfaceAPIResponse](ctx, r.client, ospf6InterfaceReqOpts, state.ID.ValueString())
	if err != nil {
		var nf *opnsense.NotFoundError
		if errors.As(err, &nf) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading an OSPFv3 interface", fmt.Sprintf("%s", err))
		return
	}
	state.fromAPI(ctx, result, state.ID.ValueString())
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *ospf6InterfaceResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state OSPF6InterfaceResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()
	if err := opnsense.Update(ctx, r.client, ospf6InterfaceReqOpts, plan.toAPI(ctx), id); err != nil {
		resp.Diagnostics.AddError("Error updating an OSPFv3 interface", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.Get[ospf6InterfaceAPIResponse](ctx, r.client, ospf6InterfaceReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading an OSPFv3 interface after update", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ospf6InterfaceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state OSPF6InterfaceResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := opnsense.Delete(ctx, r.client, ospf6InterfaceReqOpts, state.ID.ValueString()); err != nil {
		var nf *opnsense.NotFoundError
		if errors.As(err, &nf) {
			return
		}
		resp.Diagnostics.AddError("Error deleting an OSPFv3 interface", fmt.Sprintf("%s", err))
	}
}

func (r *ospf6InterfaceResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
