// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package quagga_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccOSPFArea_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { preCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_quagga_ospf_area", opnsense.ReqOpts{GetEndpoint: "/api/quagga/ospfsettings/get_area", Monad: "area"}),
		Steps: []resource.TestStep{
			{
				Config: testAccOSPFAreaConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_quagga_ospf_area.test", "id"),
			},
			{ResourceName: "opnsense_quagga_ospf_area.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccOSPFAreaConfig = `

resource "opnsense_quagga_ospf_area" "test" {
  area_id = "0.0.0.1"
  type = "stub"
}
`
