// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package ipsec

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

func (r *manualSpdResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages an IPsec manual security policy (SPD) on OPNsense.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource identifier.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"enabled":          schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(true), MarkdownDescription: "Whether this SPD entry is enabled."},
			"protocol":         schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Security protocol: esp or ah (defaults to esp).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"req_id":           schema.Int64Attribute{Required: true, MarkdownDescription: "Request ID linking this policy to a tunnel."},
			"connection_child": schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "UUID of an associated connection child (optional).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"source":           schema.StringAttribute{Required: true, MarkdownDescription: "Source network (CIDR)."},
			"destination":      schema.StringAttribute{Required: true, MarkdownDescription: "Destination network (CIDR)."},
			"description":      schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Description.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}
