// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package ipsec_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccManualSPD_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_ipsec_manual_spd", opnsense.ReqOpts{GetEndpoint: "/api/ipsec/manual_spd/get", Monad: "spd"}),
		Steps: []resource.TestStep{
			{
				Config: testAccManualSPDConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_ipsec_manual_spd.test", "id"),
			},
			{ResourceName: "opnsense_ipsec_manual_spd.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccManualSPDConfig = `

resource "opnsense_ipsec_manual_spd" "test" {
  req_id = 100
  source = "10.1.0.0/24"
  destination = "10.2.0.0/24"
  description = "tf-acc-spd"
}
`
