// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package ipsec

import (
	"context"
	"errors"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var (
	_ resource.Resource                = &manualSpdResource{}
	_ resource.ResourceWithImportState = &manualSpdResource{}
)

var manualSpdReqOpts = opnsense.ReqOpts{
	AddEndpoint:         "/api/ipsec/manual_spd/add",
	GetEndpoint:         "/api/ipsec/manual_spd/get",
	UpdateEndpoint:      "/api/ipsec/manual_spd/set",
	DeleteEndpoint:      "/api/ipsec/manual_spd/del",
	SearchEndpoint:      "/api/ipsec/manual_spd/search",
	ReconfigureEndpoint: "/api/ipsec/service/reconfigure",
	Monad:               "spd",
}

type manualSpdResource struct{ client *opnsense.Client }

func newManualSPDResource() resource.Resource { return &manualSpdResource{} }

func (r *manualSpdResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_ipsec_manual_spd"
}

func (r *manualSpdResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	r.client = client
}

func (r *manualSpdResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan ManualSPDResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	uuid, err := opnsense.Add(ctx, r.client, manualSpdReqOpts, plan.toAPI(ctx))
	if err != nil {
		resp.Diagnostics.AddError("Error creating an IPsec manual security policy (SPD)", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.Get[manualSpdAPIResponse](ctx, r.client, manualSpdReqOpts, uuid)
	if err != nil {
		resp.Diagnostics.AddError("Error reading an IPsec manual security policy (SPD) after create", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, uuid)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *manualSpdResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state ManualSPDResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	result, err := opnsense.Get[manualSpdAPIResponse](ctx, r.client, manualSpdReqOpts, state.ID.ValueString())
	if err != nil {
		var nf *opnsense.NotFoundError
		if errors.As(err, &nf) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading an IPsec manual security policy (SPD)", fmt.Sprintf("%s", err))
		return
	}
	state.fromAPI(ctx, result, state.ID.ValueString())
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *manualSpdResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state ManualSPDResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()
	if err := opnsense.Update(ctx, r.client, manualSpdReqOpts, plan.toAPI(ctx), id); err != nil {
		resp.Diagnostics.AddError("Error updating an IPsec manual security policy (SPD)", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.Get[manualSpdAPIResponse](ctx, r.client, manualSpdReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading an IPsec manual security policy (SPD) after update", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *manualSpdResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state ManualSPDResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := opnsense.Delete(ctx, r.client, manualSpdReqOpts, state.ID.ValueString()); err != nil {
		var nf *opnsense.NotFoundError
		if errors.As(err, &nf) {
			return
		}
		resp.Diagnostics.AddError("Error deleting an IPsec manual security policy (SPD)", fmt.Sprintf("%s", err))
	}
}

func (r *manualSpdResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
