// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package ipsec

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &manualSpdDataSource{}

type manualSpdDataSource struct{ client *opnsense.Client }

func newManualSPDDataSource() datasource.DataSource { return &manualSpdDataSource{} }

func (d *manualSpdDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_ipsec_manual_spd"
}

func (d *manualSpdDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Reads an IPsec manual security policy (SPD) on OPNsense by its UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID to look up.",
			},
			"enabled":          dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether this SPD entry is enabled."},
			"protocol":         dsschema.StringAttribute{Computed: true, MarkdownDescription: "Security protocol: esp or ah (defaults to esp)."},
			"req_id":           dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Request ID linking this policy to a tunnel."},
			"connection_child": dsschema.StringAttribute{Computed: true, MarkdownDescription: "UUID of an associated connection child (optional)."},
			"source":           dsschema.StringAttribute{Computed: true, MarkdownDescription: "Source network (CIDR)."},
			"destination":      dsschema.StringAttribute{Computed: true, MarkdownDescription: "Destination network (CIDR)."},
			"description":      dsschema.StringAttribute{Computed: true, MarkdownDescription: "Description."},
		},
	}
}

func (d *manualSpdDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *manualSpdDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config ManualSPDResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[manualSpdAPIResponse](ctx, d.client, manualSpdReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading an IPsec manual security policy (SPD)", fmt.Sprintf("Could not read an IPsec manual security policy (SPD) %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
