// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package ipsec_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccPool_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_ipsec_pool", opnsense.ReqOpts{GetEndpoint: "/api/ipsec/pools/get", Monad: "pool"}),
		Steps: []resource.TestStep{
			{
				Config: testAccPoolConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_ipsec_pool.test", "id"),
			},
			{ResourceName: "opnsense_ipsec_pool.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccPoolConfig = `

resource "opnsense_ipsec_pool" "test" {
  name = "tfaccpool"
  addresses = "10.20.30.0/24"
}
`
