// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package ipsec

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/tfconv"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

// PoolResourceModel is the Terraform state model for opnsense_ipsec_pool.
type PoolResourceModel struct {
	ID        types.String `tfsdk:"id"`
	Enabled   types.Bool   `tfsdk:"enabled"`
	Name      types.String `tfsdk:"name"`
	Addresses types.String `tfsdk:"addresses"`
	DNS       types.Set    `tfsdk:"dns"`
}

type poolAPIResponse struct {
	Enabled   string                   `json:"enabled"`
	Name      string                   `json:"name"`
	Addresses string                   `json:"addrs"`
	DNS       opnsense.SelectedMapList `json:"dns"`
}

type poolAPIRequest struct {
	Enabled   string `json:"enabled"`
	Name      string `json:"name"`
	Addresses string `json:"addrs"`
	DNS       string `json:"dns,omitempty"`
}

func (m *PoolResourceModel) toAPI(ctx context.Context) *poolAPIRequest {
	return &poolAPIRequest{
		Enabled:   opnsense.BoolToString(m.Enabled.ValueBool()),
		Name:      m.Name.ValueString(),
		Addresses: m.Addresses.ValueString(),
		DNS:       tfconv.SetToCSV(ctx, m.DNS),
	}
}

func (m *PoolResourceModel) fromAPI(_ context.Context, a *poolAPIResponse, id string) {
	m.ID = types.StringValue(id)
	m.Enabled = types.BoolValue(opnsense.StringToBool(a.Enabled))
	m.Name = types.StringValue(a.Name)
	m.Addresses = types.StringValue(a.Addresses)
	m.DNS = tfconv.SliceToSet(a.DNS)
}
