// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package ipsec

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var _ datasource.DataSource = &vtiDataSource{}

type vtiDataSource struct{ client *opnsense.Client }

func newVTIDataSource() datasource.DataSource { return &vtiDataSource{} }

func (d *vtiDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_ipsec_vti"
}

func (d *vtiDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		MarkdownDescription: "Look up an existing an IPsec virtual tunnel interface (VTI) on OPNsense by UUID.",
		Attributes: map[string]dsschema.Attribute{
			"id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID of the an IPsec virtual tunnel interface (VTI) to look up.",
			},
			"enabled":        dsschema.BoolAttribute{Computed: true, MarkdownDescription: "Whether this VTI is enabled."},
			"req_id":         dsschema.Int64Attribute{Computed: true, MarkdownDescription: "Unique request ID for this tunnel."},
			"local":          dsschema.StringAttribute{Computed: true, MarkdownDescription: "Local gateway IP address."},
			"remote":         dsschema.StringAttribute{Computed: true, MarkdownDescription: "Remote gateway IP address."},
			"tunnel_local":   dsschema.StringAttribute{Computed: true, MarkdownDescription: "Local tunnel (inside) IP address."},
			"tunnel_remote":  dsschema.StringAttribute{Computed: true, MarkdownDescription: "Remote tunnel (inside) IP address."},
			"tunnel_local2":  dsschema.StringAttribute{Computed: true, MarkdownDescription: "Optional second local tunnel IP address."},
			"tunnel_remote2": dsschema.StringAttribute{Computed: true, MarkdownDescription: "Optional second remote tunnel IP address."},
			"description":    dsschema.StringAttribute{Computed: true, MarkdownDescription: "Description."},
		},
	}
}

func (d *vtiDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	d.client = client
}

func (d *vtiDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config VTIResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := config.ID.ValueString()
	result, err := opnsense.Get[vtiAPIResponse](ctx, d.client, vtiReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading an IPsec virtual tunnel interface (VTI)", fmt.Sprintf("Could not read an IPsec virtual tunnel interface (VTI) %s: %s", id, err))
		return
	}
	config.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
