// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package ipsec

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

func (r *vtiResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages an IPsec virtual tunnel interface (VTI) on OPNsense.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource identifier.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"enabled":        schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(true), MarkdownDescription: "Whether this VTI is enabled."},
			"req_id":         schema.Int64Attribute{Required: true, MarkdownDescription: "Unique request ID for this tunnel."},
			"local":          schema.StringAttribute{Required: true, MarkdownDescription: "Local gateway IP address."},
			"remote":         schema.StringAttribute{Required: true, MarkdownDescription: "Remote gateway IP address."},
			"tunnel_local":   schema.StringAttribute{Required: true, MarkdownDescription: "Local tunnel (inside) IP address."},
			"tunnel_remote":  schema.StringAttribute{Required: true, MarkdownDescription: "Remote tunnel (inside) IP address."},
			"tunnel_local2":  schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Optional second local tunnel IP address.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"tunnel_remote2": schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Optional second remote tunnel IP address.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"description":    schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Description.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}
