// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package ipsec

import (
	"context"
	"errors"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

var (
	_ resource.Resource                = &vtiResource{}
	_ resource.ResourceWithImportState = &vtiResource{}
)

var vtiReqOpts = opnsense.ReqOpts{
	AddEndpoint:         "/api/ipsec/vti/add",
	GetEndpoint:         "/api/ipsec/vti/get",
	UpdateEndpoint:      "/api/ipsec/vti/set",
	DeleteEndpoint:      "/api/ipsec/vti/del",
	SearchEndpoint:      "/api/ipsec/vti/search",
	ReconfigureEndpoint: "/api/ipsec/service/reconfigure",
	Monad:               "vti",
}

type vtiResource struct{ client *opnsense.Client }

func newVTIResource() resource.Resource { return &vtiResource{} }

func (r *vtiResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_ipsec_vti"
}

func (r *vtiResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	r.client = client
}

func (r *vtiResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan VTIResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	uuid, err := opnsense.Add(ctx, r.client, vtiReqOpts, plan.toAPI(ctx))
	if err != nil {
		resp.Diagnostics.AddError("Error creating an IPsec virtual tunnel interface (VTI)", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.Get[vtiAPIResponse](ctx, r.client, vtiReqOpts, uuid)
	if err != nil {
		resp.Diagnostics.AddError("Error reading an IPsec virtual tunnel interface (VTI) after create", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, uuid)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *vtiResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state VTIResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	result, err := opnsense.Get[vtiAPIResponse](ctx, r.client, vtiReqOpts, state.ID.ValueString())
	if err != nil {
		var nf *opnsense.NotFoundError
		if errors.As(err, &nf) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading an IPsec virtual tunnel interface (VTI)", fmt.Sprintf("%s", err))
		return
	}
	state.fromAPI(ctx, result, state.ID.ValueString())
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *vtiResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state VTIResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()
	if err := opnsense.Update(ctx, r.client, vtiReqOpts, plan.toAPI(ctx), id); err != nil {
		resp.Diagnostics.AddError("Error updating an IPsec virtual tunnel interface (VTI)", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.Get[vtiAPIResponse](ctx, r.client, vtiReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading an IPsec virtual tunnel interface (VTI) after update", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *vtiResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state VTIResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := opnsense.Delete(ctx, r.client, vtiReqOpts, state.ID.ValueString()); err != nil {
		var nf *opnsense.NotFoundError
		if errors.As(err, &nf) {
			return
		}
		resp.Diagnostics.AddError("Error deleting an IPsec virtual tunnel interface (VTI)", fmt.Sprintf("%s", err))
	}
}

func (r *vtiResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
