// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package ipsec_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/matthew-on-git/terraform-provider-opnsense/internal/acctest"
	"github.com/matthew-on-git/terraform-provider-opnsense/pkg/opnsense"
)

func TestAccVTI_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_ipsec_vti", opnsense.ReqOpts{GetEndpoint: "/api/ipsec/vti/get", Monad: "vti"}),
		Steps: []resource.TestStep{
			{
				Config: testAccVTIConfig,
				Check:  resource.TestCheckResourceAttrSet("opnsense_ipsec_vti.test", "id"),
			},
			{ResourceName: "opnsense_ipsec_vti.test", ImportState: true, ImportStateVerify: true},
		},
	})
}

const testAccVTIConfig = `

resource "opnsense_ipsec_vti" "test" {
  req_id = 100
  local = "192.168.56.10"
  remote = "192.0.2.50"
  tunnel_local = "10.0.0.1"
  tunnel_remote = "10.0.0.2"
  description = "tf-acc-vti"
}
`
