package main

import "strings"

// camelName converts a snake_case file prefix into a lowerCamel identifier base
// used for unexported type names (e.g. "ospf_network" -> "ospfNetwork").
func camelName(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if i == 0 || p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

const header = `// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package {{.Pkg}}
`

const testText = `// Code generated by internal/generate; DO NOT EDIT.
// Copyright (c) Matthew Mellor
// SPDX-License-Identifier: MPL-2.0

package {{.Pkg}}_test

import (
{{.Imports}}
)

func TestAcc{{.R.GoType}}_basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		PreCheck:                 func() { acctest.PreCheck(t) },
{{if isItem .R}}		CheckDestroy:             acctest.CheckResourceDestroyed(t, "opnsense_{{.R.TypeName}}", opnsense.ReqOpts{GetEndpoint: "{{index .R.Endpoints "get"}}", Monad: "{{.R.Monad}}"}),
{{end}}		Steps: []resource.TestStep{
			{
				Config: testAcc{{.R.GoType}}Config,
				Check:  resource.TestCheckResourceAttrSet("opnsense_{{.R.TypeName}}.test", "id"),
			},
			{ResourceName: "opnsense_{{.R.TypeName}}.test", ImportState: true, {{if isSingleton .R}}ImportStateId: "{{.R.ID}}", {{end}}ImportStateVerify: true},
		},
	})
}

const testAcc{{.R.GoType}}Config = ` + "`" + `
resource "opnsense_{{.R.TypeName}}" "test" {
{{testFields .R}}}
` + "`" + `
`

const modelText = header + `
import (
{{.Imports}}
)

// {{.R.GoType}}ResourceModel is the Terraform state model for opnsense_{{.R.TypeName}}.
type {{.R.GoType}}ResourceModel struct {
	ID types.String ` + "`tfsdk:\"id\"`" + `
{{range .R.Fields}}	{{.Name}} {{goType .}} ` + "`tfsdk:\"{{.TF}}\"`" + `
{{end}}}

type {{camel .R.Name}}APIResponse struct {
{{range .R.Fields}}	{{.Name}} {{respType .}} ` + "`json:\"{{.JSON}}\"`" + `
{{end}}}

type {{camel .R.Name}}APIRequest struct {
{{range .R.Fields}}	{{.Name}} string {{reqTag .}}
{{end}}}

func (m *{{.R.GoType}}ResourceModel) toAPI({{if hasSet .R}}ctx{{else}}_{{end}} context.Context) *{{camel .R.Name}}APIRequest {
	return &{{camel .R.Name}}APIRequest{
{{range .R.Fields}}		{{.Name}}: {{toAPI .}},
{{end}}	}
}

func (m *{{.R.GoType}}ResourceModel) fromAPI(_ context.Context, a *{{camel .R.Name}}APIResponse, id string) {
	m.ID = types.StringValue(id)
{{range .R.Fields}}	{{fromAPI .}}
{{end}}}
`

const schemaText = header + `
import (
{{.Imports}}
)

func (r *{{camel .R.Name}}Resource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: {{printf "%q" (printf "Manages %s on OPNsense." .R.Title)}},
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource identifier.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
{{range .R.Fields}}			{{schemaAttr .}}
{{end}}		},
	}
}
`

const resourceText = header + `
import (
{{.Imports}}
)

{{$n := camel .R.Name}}var (
	_ resource.Resource                = &{{$n}}Resource{}
	_ resource.ResourceWithImportState = &{{$n}}Resource{}
)
{{if isSingleton .R}}
// {{$n}}ID is the synthetic identifier for this singleton settings object.
const {{$n}}ID = {{printf "%q" .R.ID}}
{{end}}
var {{$n}}ReqOpts = opnsense.ReqOpts{
{{if isItem .R}}	AddEndpoint:         {{printf "%q" (index .R.Endpoints "add")}},
{{end}}	GetEndpoint:         {{printf "%q" (index .R.Endpoints "get")}},
	UpdateEndpoint:      {{printf "%q" (index .R.Endpoints "set")}},
{{if isItem .R}}	DeleteEndpoint:      {{printf "%q" (index .R.Endpoints "del")}},
	SearchEndpoint:      {{printf "%q" (index .R.Endpoints "search")}},
{{end}}	ReconfigureEndpoint: {{printf "%q" .R.Reconfigure}},
	Monad:               {{printf "%q" .R.Monad}},
}

type {{$n}}Resource struct{ client *opnsense.Client }

func new{{.R.GoType}}Resource() resource.Resource { return &{{$n}}Resource{} }

func (r *{{$n}}Resource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_{{.R.TypeName}}"
}

func (r *{{$n}}Resource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*opnsense.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *opnsense.Client.")
		return
	}
	r.client = client
}
{{if isItem .R}}
func (r *{{$n}}Resource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan {{.R.GoType}}ResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	uuid, err := opnsense.Add(ctx, r.client, {{$n}}ReqOpts, plan.toAPI(ctx))
	if err != nil {
		resp.Diagnostics.AddError("Error creating {{.R.Title}}", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.Get[{{$n}}APIResponse](ctx, r.client, {{$n}}ReqOpts, uuid)
	if err != nil {
		resp.Diagnostics.AddError("Error reading {{.R.Title}} after create", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, uuid)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *{{$n}}Resource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state {{.R.GoType}}ResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	result, err := opnsense.Get[{{$n}}APIResponse](ctx, r.client, {{$n}}ReqOpts, state.ID.ValueString())
	if err != nil {
		var nf *opnsense.NotFoundError
		if errors.As(err, &nf) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading {{.R.Title}}", fmt.Sprintf("%s", err))
		return
	}
	state.fromAPI(ctx, result, state.ID.ValueString())
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *{{$n}}Resource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state {{.R.GoType}}ResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()
	if err := opnsense.Update(ctx, r.client, {{$n}}ReqOpts, plan.toAPI(ctx), id); err != nil {
		resp.Diagnostics.AddError("Error updating {{.R.Title}}", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.Get[{{$n}}APIResponse](ctx, r.client, {{$n}}ReqOpts, id)
	if err != nil {
		resp.Diagnostics.AddError("Error reading {{.R.Title}} after update", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *{{$n}}Resource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state {{.R.GoType}}ResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := opnsense.Delete(ctx, r.client, {{$n}}ReqOpts, state.ID.ValueString()); err != nil {
		var nf *opnsense.NotFoundError
		if errors.As(err, &nf) {
			return
		}
		resp.Diagnostics.AddError("Error deleting {{.R.Title}}", fmt.Sprintf("%s", err))
	}
}

func (r *{{$n}}Resource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
{{else}}
func (r *{{$n}}Resource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan {{.R.GoType}}ResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := opnsense.UpdateSingleton(ctx, r.client, {{$n}}ReqOpts, plan.toAPI(ctx)); err != nil {
		resp.Diagnostics.AddError("Error applying {{.R.Title}}", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.GetSingleton[{{$n}}APIResponse](ctx, r.client, {{$n}}ReqOpts)
	if err != nil {
		resp.Diagnostics.AddError("Error reading {{.R.Title}} after apply", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, {{$n}}ID)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *{{$n}}Resource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state {{.R.GoType}}ResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	result, err := opnsense.GetSingleton[{{$n}}APIResponse](ctx, r.client, {{$n}}ReqOpts)
	if err != nil {
		var nf *opnsense.NotFoundError
		if errors.As(err, &nf) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading {{.R.Title}}", fmt.Sprintf("%s", err))
		return
	}
	state.fromAPI(ctx, result, {{$n}}ID)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *{{$n}}Resource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan {{.R.GoType}}ResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := opnsense.UpdateSingleton(ctx, r.client, {{$n}}ReqOpts, plan.toAPI(ctx)); err != nil {
		resp.Diagnostics.AddError("Error updating {{.R.Title}}", fmt.Sprintf("%s", err))
		return
	}
	result, err := opnsense.GetSingleton[{{$n}}APIResponse](ctx, r.client, {{$n}}ReqOpts)
	if err != nil {
		resp.Diagnostics.AddError("Error reading {{.R.Title}} after update", fmt.Sprintf("%s", err))
		return
	}
	plan.fromAPI(ctx, result, {{$n}}ID)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// Delete is a no-op for the singleton; destroy only removes it from state.
func (r *{{$n}}Resource) Delete(_ context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse) {
}

func (r *{{$n}}Resource) ImportState(ctx context.Context, _ resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), types.StringValue({{$n}}ID))...)
}
{{end}}`
